### ISSUE TITLE
Conflict with toggle shortcodes plugins

### ISSUE THREAD

**Issue by pcwriter** [boonebgorges/buddypress-docs#121]
@boonebgorges

Thanks for another fine plugin! I have one small issue that may be a js conflict... but I'm no expert when it comes to js!

I'm using J-Shortcodes and TheTheFly shortcode plugins for toggles and accordions on a new site I'm putting together. When on the "create" or "edit" pages, the toggles and accordions go haywire. However, when on the "view all" page, everything is OK. 

Below are a few screenshots to illustrate the problem. Any ideas?

http://i1137.photobucket.com/albums/n511/pcwriter/kwitterz-1/Capture1.png "Help" button - OK
http://i1137.photobucket.com/albums/n511/pcwriter/kwitterz-1/Capture2.png "Help" content open - OK
http://i1137.photobucket.com/albums/n511/pcwriter/kwitterz-1/Capture3.png "Help" button gone and content all screwed up

**Comment by boonebgorges** [comment]
With apologies for leaving this ticket hanging for all these years (!), I'm going to close it out. If there's still an active problem, feel free to reopen with details.
