### ISSUE TITLE
html content disappear after submiting

### ISSUE THREAD

**Issue by asafche** [boonebgorges/buddypress-docs#157]
after i'm writing some content in the visual editor, i switch to the html editor and embed an iframe.
after saving the iframe is gone. something is filtering the iframe out? maybe the tinyMCE?

**Comment by boonebgorges** [comment]
Sorry I missed this ticket so many years ago! It sounds to me like WordPress is filtering based on allowed tags. If this turns out to be a problem with Docs specifically, please provide steps to reproduce.
