### ISSUE TITLE
Other taxonomies intergartion

### ISSUE THREAD

**Issue by imjjss** [boonebgorges/buddypress-docs#164]
Currently, terms under other taxonomies can be partially handled correctly by doc_tags if use extends class of BP_Docs_Taxonomy. However, some details not playing out nicely--
docs-filter deosn't reflect the other taxonomy, it only repeat doc_tags's filter box. 
The 2nd Tag Cloud can refelct the other taxonomy, if click a term, can get correct URL  and redirect to correct tab, but can't find the doc. 
The above 2 aspects is difficult to fix in extends class unless Doc provides an argument at places where it uses "$this->docs_tag_tax_name"

**Comment by boonebgorges** [comment]
Mixing terms between different object types is murky waters, and not something I'd like to support directly in Docs. If there are filters in Docs thtat would make this easier, please provide specific details.
