### ISSUE TITLE
List BP Docs under existing content

### ISSUE THREAD

**Issue by gepsinger** [boonebgorges/buddypress-docs#166]
Hi, 

first of all: i really love your plugin! I really enjoy working with it and am thankful for all the work you put in it!

I have a feature request (or question) though: How can I find a BP Doc when I insert or edit a link under the section of "Or link to existing content". My pages and posts show up there. If I install a Wiki Plugin like Wiki light e.g the "wiki pages" show up there as well. But BP Docs don't make an occurance there. 

Is this a request for a new feature or do I miss something!?

Thanks for your help

Gepsinger

**Comment by boonebgorges** [comment]
It appears that this was fixed in 56179d56a1ea1ca1f3690887c66bd36b60804426.
