### ISSUE TITLE
a simple index

### ISSUE THREAD

**Issue by julianamoreira** [boonebgorges/buddypress-docs#186]
Feature request/idea: A way to create a simple index of the created documents (by title, author and tags). I would like to have the possibility to show all the documents filtred by, for example, the author and then when I choose the author, the plugin gets me all the documents writen by the author.

**Comment by boonebgorges** [comment]
I'd love to build something like this, but it's a huge lift. If someone was interested in taking on the challenge, it could be done first as a separate plugin.
