### ISSUE TITLE
"Doc Creator only" edit permissions not working

### ISSUE THREAD

**Issue by ostephens** [boonebgorges/buddypress-docs#199]
A user creates a document (settings allow any group member to create docs), then sets the edit rights to "Doc Creator only". After this they are themselves unable to edit the document.

Admin can continue to edit the document, and the doc creator is listed as the correct user.

**Comment by boonebgorges** [comment]
Going to close this one due to inactivity, but if problems are still occurring and we think they're due to Docs, please reopen with details and we'll trudge through.
