### ISSUE TITLE
Subdirectories for Docs

### ISSUE THREAD

**Issue by nickharambee** [boonebgorges/buddypress-docs#208]
Hi,

I am wondering whether you have considered adding an option for users to create subdirectories for docs within Buddypress Docs.  I am aware of the parent/child and tagging features, I just think that organising docs into directories, perhaps with a option to have tabs for these directories, would suit my needs best. 

Thanks for a great plugin,

Nick

**Comment by boonebgorges** [comment]
Folders were introduced for group contexts a couple versions ago.
