### ISSUE TITLE
Embedding PDF and Word Docs in Buddypress Docs

### ISSUE THREAD

**Issue by nickharambee** [boonebgorges/buddypress-docs#213]
I am wondering if there is a plugin for/method of embedding PDFs and Word documents into Buddypress docs. Presumably I could use a service like Scribd to do so, but I am wondering about other methods. 

I have installed the Google Doc Embedder plugin which adds an item to the TinyMCE toolbar for embedding PDFs and Docs into standard WP pages, but it doesn't show in the TinyMCE toolbar for BP Docs. Is there a way of enabling this, or another similar method of achieving embedding such files?

Thanks,

Nick

**Comment by rn2web** [comment]
did anyone have sucess with this request?
