### ISSUE TITLE
Long URL in first line of docs forces title column in list view of docs to be oversized

### ISSUE THREAD

**Issue by nickharambee** [boonebgorges/buddypress-docs#218]
One user created a couple of docs with a long URL in the first line of the document, and in the list view of all docs for that group, the width of the title column was forced above 30% to accommodate the URL in the summary of the content of the documents.  This meant that the whole table was forced off the edge of the page.

I have added this as a workaround fix:

.title-cell {
    max-width: 343px !important;
    overflow: hidden !important;
}

For some reason I couldn't use max-width of 30% - the column didn't obey this, whereas it does for pixels.  I used max-width: 343px as this is the maximum width that the column resizes to when my site is at its maximum width.  Setting a max-width by pixels isn't ideal though as I have a variable width design for my site, and when the site approaches it's minimum width some of the content of the table still falls off the page.

Is there a better workaround/solution to this (other than asking users not to add long urls in the first couple of lines of a document!)?

Thanks,

Nick

**Comment by boonebgorges** [comment]
Sorry for losing track of this ticket! Your workarounds are about as good a solution as I can think of.
