### ISSUE TITLE
Error in CodeStyling Localization

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#262]
While using BP Docs 1.2.7 together with CodyStyling Localization 1.99.29 (CSL) I've got the following error in CSL:
DEPRECATED Error: [8192] Assigning the return value of new by reference is deprecated …/wp-content/plugins/buddypress-docs/bp-docs.php on line 344

**Comment by boonebgorges** [comment]
I think this was fixed some time ago :-D
