### ISSUE TITLE
page_id function doesn't work anymore

### ISSUE THREAD

**Issue by fkapnist** [boonebgorges/buddypress-docs#265]
I was using the "page_id" shortcode to link to BuddyPress Docs. But with version 1.2.8 the page_id function doesn't work anymore. I have many links like this within several websites and I don't want to have to redo them all by hand. Any advice?

**Comment by boonebgorges** [comment]
Sorry this ticket has been neglected all this time - I'm unfamiliar with the `page_id` shortcode. Perhaps it came from a third-party plugin?
