### ISSUE TITLE
bp_docs_user_can

### ISSUE THREAD

**Issue by imjjss** [boonebgorges/buddypress-docs#267]
I'm trying to use the function bp_docs_current_user_can and found the argument $doc_id is set to false on line 246 in bp_docs_user_can.

This seems to me the $doc_id will be set to false disregarding what argument is provided. So, does it mean we can't use this function for other docs than currently being viewed doc?

**Comment by boonebgorges** [comment]
In most places, I've moved toward the use of `current_user_can()`, passing the item ID properly.
