### ISSUE TITLE
After upgrade Docs not associated properly

### ISSUE THREAD

**Issue by daisypeel** [boonebgorges/buddypress-docs#268]
After upgrading, as admin I can see docs in groups, but other members of a group cannot. If I go in and reassociate docs in the front end, that fixes it, although in the dashboard they're already associated. Not sure why this should be happening, but going and fixing each one individually is going to be tedious :(

**Comment by boonebgorges** [comment]
Sorry I was unable to help with this. If the problem persists, perhaps we can pick up the thread.
