### ISSUE TITLE
wrong post referenced in edit mode

### ISSUE THREAD

**Issue by wdfee** [boonebgorges/buddypress-docs#269]
Hi Boone,
when editing a doc the wrong article details are displayed (for ID, title, content, slug and so on).
I tried this out and it worked for me:
In file /templates/single/edit.php I called the_post() again in line 2:
`<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); endwhile; endif; ?>`
Now the correct post informaiton is displayed. (I don't know if it matters: The wrong displayed post from before was a post of courseware plugin. Maybe there is a reference conflict.)

**Comment by boonebgorges** [comment]
Hi Fée - I'm closing out some old tickets - sorry I didn't get around to figuring this out. Please reopen if the problem persists.
