### ISSUE TITLE
Further Notifications - Feature Request

### ISSUE THREAD

**Issue by websitehelperuk** [boonebgorges/buddypress-docs#301]
FR - To add additional notifications
- When user submits new Doc website admin to be notified
- When user edits/updates Doc website admin to be notified

Groups 
- When user submits new Doc group admin/moderator(s) to be notified
- When user edits/updates Doc group admin/moderator(s) to be notified

**Comment by boonebgorges** [comment]
Related: #162 

These specific emails are likely undesirable for most Docs installations, so I think it's best to leave their implementation to plugin authors.
