### ISSUE TITLE
My host technician suggested me to remove Buddypress Docs or it will destroy my whole site

### ISSUE THREAD

**Issue by hudaizhi** [boonebgorges/buddypress-docs#352]
I really love this plugin! And it really worked well for a long time, but these days I can not login into my WP dashboard and my host technician said it was because this plugin. And he deactivated it and then all went well. He suggested me remove it. I really love this plugin and today I reinstalled it but it destroy my site again. And with the help from my technician, we deactivate it again. How can this be happening! What a pity to leave a site without this plugin! Could you or anybody help me out?

My site is http://lingdaoli.com. 

With hope I am looking forward to any help here.

**Comment by boonebgorges** [comment]
Hi @hudaizhi - I hope you managed to get your problem sorted. I'm closing some old tickets, but please feel free to leave an update here if there are more questions.
