### ISSUE TITLE
Buddypress docs Front End Edit button not working

### ISSUE THREAD

**Issue by alimpic** [boonebgorges/buddypress-docs#361]
First let me say that I think that this plugin is one of the essentials for websites that uses Buddypress.

However I run into a problem. When I click on the Edit button on the front-end editor wanting to change existing doc, like adding new attachment or editing text, nothing hapend, like this button does not work, although in url bar stand for example: "http://www.website.com/docs/test/edit"

**Comment by boonebgorges** [comment]
Closing this ticket due to inactivity.
