### ISSUE TITLE
Auto-suggest Links to Existing BP Docs Content when clicking hyperlink icon - New featue request

### ISSUE THREAD

**Issue by vothsco** [boonebgorges/buddypress-docs#376]
CBOX member Daniel notices how nice it is in the Group Forums when you want to create a link and you have the option to pick from a drop down list of existing forum topics.  It would be nice if this functionality could also be added to BP Docs and to the Docs Wiki.

Here is the link:
http://commonsinabox.org/groups/help-support/forum/topic/linking-to-docs-from-other-docs/

**Comment by boonebgorges** [comment]
This was added to Docs a few versions ago.
