### ISSUE TITLE
Cannot Upload files

### ISSUE THREAD

**Issue by exiguus** [boonebgorges/buddypress-docs#428]
Attachment upload Button fails in doc/edit with javascript error:

```
TypeError: file_frame is undefined
Library = file_frame.states.get('library');
```

Fix buddypress-docs/includes/js/attachments.js
Remove line 63 and 73 (jquery document ready function)

```
...
        wp.media.ajax( 'bp_docs_create_dummy_doc', options );
    }
        file_frame = new BP_Docs_MediaFrame({
            title: bp_docs_attachments.upload_title,
            button: {
                text: bp_docs_attachments.upload_button,
            },
            multiple: false
        });

        Library = file_frame.states.get('library');
})(jQuery);
```

**Comment by boonebgorges** [comment]
Sorry for not responding to this issue. I'm not seeing the bug in current versions of Docs, so I'm assuming it was either a quirk of the installation or something that's been fixed since.
