### ISSUE TITLE
Associated group ID

### ISSUE THREAD

**Issue by Mamaduka** [boonebgorges/buddypress-docs#429]
This issue is related to folders branch.

When using groups hierarchy `$associated_group_id` is empty string and folders selector is forced to return global folders. This is caused, because URL might look like this - `group=working-groups/securities-lending`. Possible solution:

```
$slug = explode( '/', $_GET['group'] );
$group_id = BP_Groups_Group::get_id_from_slug( end( $slug ) );
```

Another issue is that, where creating docs from "global" page ( e.g. http://bp.loc/docs/create/ ), associated group isn't set. Possible solution is to add JS listener to "Associated Groups" and reload folders on change.

**Update**
Second one is fake, this functionality is already in code.

**Comment by boonebgorges** [comment]
Really sorry for not responding to this earlier, @Mamaduka. Slugs with slashes suggest that the site is using a group hierarchy plugin. @dcavins Since you've worked in this area, could you give this one a think to see if there's anything special that needs to be done for support there?

**Comment by dcavins** [comment]
BP Docs works well with my updated hierarchy plugin (at least I'm unaware of outstanding bugs):
https://github.com/dcavins/hierarchical-groups-for-bp

But, yes, there were some problems with the older BP Group Hierarchy plugin.

**Comment by boonebgorges** [comment]
Cool - I'm going to close this one, then, because I don't think we need to go out of the way to support the old plugin.
