### ISSUE TITLE
How to hide /docs directory for logged out users?

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#430]
Hi Boone,
Would you please provide a few lines of code to hide the /docs directory for logged out users?
Thanks for help,
Hans

**Comment by boonebgorges** [comment]
Hi @schwarzaufweiss - Many apologies for not responding to this. I don't recall seeing it come through (I think there was a period when GitHub wasn't sending email notifications). Anyway, that's not a good excuse for the tardiness. Here is a snippet that should work:

`
add_action( 'bp_template_redirect', function() {
    if ( bp_docs_is_global_directory() && ! is_user_logged_in() ) {
        bp_core_redirect( bp_get_root_domain() );
    }
} );
`
