### ISSUE TITLE
After WP 4.0 Update Some doc links are broken 

### ISSUE THREAD

**Issue by vothsco** [boonebgorges/buddypress-docs#431]
CBOX member Matt Brooks reports that after upgrading to WP 4.0 some, but not all his group docs are not working.  Upon clicking, he gets the  “Darn it.. Nothing found” page.

Here is a link to the thread:http://commonsinabox.org/groups/help-support/forum/topic/wordpress-4/#post-5202

**Comment by boonebgorges** [comment]
I haven't heard this recur, so I'm going to close.
