### ISSUE TITLE
feature request: simultaneous collaboration

### ISSUE THREAD

**Issue by rcrath** [boonebgorges/buddypress-docs#434]
I checked to see if this has come up before and it does not seem to have.  I am testing Commons in a box to see whether to make the move from a moodle install I have used for several years.  I use the wiki functionaility for doing groupwork in my classes (upper division undergrad).  Students spend class time in small groups creating wiki pages and linking them to each other.  The single user + lockout is confusing and frustrating for students in this context in moodle, as they simply can't edit when someone else is on the doc. Often a group will have multiple people with laptops, but because of the lockout, one person is relegated to the role of "writer" and can't really participate actively while keeping up with others' contributions. Our workaround is to do the group writing in google docs, and then cutting and pasting into the wiki.  I also tried just using Google docs outright once, but was not satisfied with the way it structures linking and sharing. Cut-and-paste from google docs to wiki works but is clunky and addds an extra layer of complexity to the writing process.  

WHat  would be a most useful feature in our context would be incorporating google docs/etherpad/google wave simultaneous edits in the wiki, while maintaining the simpler linking structure of the wiki format (single click executes link in wiki, single click raises popup to follow/edit/remove link in google docs).

Thank you for your consideration and for writing what looks like a very useful application of wp.

**Comment by boonebgorges** [comment]
Integration with Etherpad and the like would almost certainly have to happen in a separate plugin. I'd love to do this, but it won't happen without there being a patron supporting that work.
