### ISSUE TITLE
Filename unreadable, code problem

### ISSUE THREAD

**Issue by y1k2y3** [boonebgorges/buddypress-docs#436]
When I upload a file named in English, the plugin just works perfect. But if I uploaded a file named in Chinese,  the front-end displays only ".ext". In the filesystem, I could found the file I just uploaded does exist. But the filename is unreadable. 
I copied the filename to a text editor found out the filename is in ANSI code, though the whole site is in UTF-8. Other upload way such as wordpress's media library and gallary plugin works normally witha UTF-8 filename. 
Is there anyway to solve this? Any suggestion is appreciated~

**Comment by boonebgorges** [comment]
Thanks for the file. I'll try to look at this soon.

**Comment by boonebgorges** [comment]
Sorry I have been unable to research this. If the problem persists, please feel free to leave further details.
