### ISSUE TITLE
attachments: media library in frontend empty for non docs

### ISSUE THREAD

**Issue by wdfee** [boonebgorges/buddypress-docs#437]
Hi Boone,
in use with another plugin the media library is not accessibe, there's an fatal error (visible only in ajax POST through firebug).
I went through your code, testing: get_doc_id_from_url() can only be called in an existing doc, so in attachments.php the line 312 crashes. It works if I change line 311 to this:
`} elseif ( bp_docs_is_existing_doc() ) {`

**Comment by boonebgorges** [comment]
Thanks, Fee - I can see that there may be a problem here, but I'm not 
100% certain that your suggested fix is right - it seems to me that the 
Docs AJAX should not be running at all when looking at non-Docs.

Can you give me more detailed instructions to reproduce? Which plugin 
are you using, and what are the specific actions you have to take to 
cause the error?

**Comment by wdfee** [comment]
Hi Boone, just stumbled over this by checking again - The issue does not appear anymore. I think we can close it.
