### ISSUE TITLE
Associate Document with Multiple Groups

### ISSUE THREAD

**Issue by evanheisler** [boonebgorges/buddypress-docs#443]
I see this has come up a bit in the past, but is not currently a feature. We have a need to associate a single doc with multiple groups, so users across groups would be notified and have access to the same item. 

I think [if this is the primary reason](https://github.com/boonebgorges/buddypress-docs/issues/286#issuecomment-14239303) what about using a different set of access controls altogether for multiple groups? If it were simplified to only be members of the identified groups, that seems like a reasonable first pass.

**Comment by boonebgorges** [comment]
The underlying infrastructure will mostly allow for this already. The 
challenge is the UI. What would it look like to associate with more than 
one group? What does it look like to have "a different set of access 
controls altogether for multiple groups"?

There's also a question of what to do with activity items. Do we create 
more than one activity item - one for each group?

Thoughts, patches, wireframes, proofs-of-concept welcome :)

**Comment by evanheisler** [comment]
Thanks for the quick reply and interest @boonebgorges. In our case, we will probably start with simplified permissions. I was envisioning a toggle for "Associate with One Group/Multiple Groups". If the user selects multiple groups, they are shown an alert that says "This document and comments will be __read only__ for the selected groups' members. Members can also __post comments__. Admins and group moderators will have __edit__ permissions." Then present them with a multi select list of available groups.

Maybe ours is an edge case, but it seems reasonable (for starters) to fix the permissions when associating with multiple groups because of all the combinations of permissions. I also might be over-simplifying. As for the generated activity, I think 1 document = 1 activity, either with a list of the associated groups or the basic activity of "[user] created the doc [title]". If a group is private or hidden, that privacy should trump another groups' more open visibility setting.

I started digging into this a bit and trying to understand `bp_docs_associated_item`. I see that its ready to accept an array of values, but its been slow going trying to send an array and get the requisite rows into `term_relationships`. I'll update if I have anything more concrete to share.

**Comment by boonebgorges** [comment]
Thanks for the update - looking forward to seeing what progress you make.

**Comment by boonebgorges** [comment]
Related: #124.

I'm going to close this ticket as it's unlikely that I will be able to take on this task in the foreseeable future. If someone steps forward to do the technical work, we can reopen.
