### ISSUE TITLE
Can't Upload Docs

### ISSUE THREAD

**Issue by Mat2012** [boonebgorges/buddypress-docs#447]
Hi Gorges,

I'm back (unfortunately). The problem that I explained in this thread : https://github.com/boonebgorges/buddypress-docs/issues/446 appears to be a real one (at last, in my case).

- Install on MAMP
- Last versions of BuddyPress and WordPress activated
- All plugins deactivated except BuddyPress
- Theme : Twenty Fifteen

To keep it simple : after activating BP-Docs, I can't upload any docs or image, wherever in my site (not only on Documents custom post types) in backend and frontend. 

I click on upload, the file seem to be loaded, but, then, I've this message ("Error, please try later"):
![buddypress docs 2015-03-06 16-26-08](https://cloud.githubusercontent.com/assets/1023932/6528247/f4d15dfc-c420-11e4-8301-4ee366949be1.png)

Can you help me ? If I can help you to understand the origin of the problem, just ask.

**Comment by boonebgorges** [comment]
Do you have any problems uploading normal images, through Dashboard > 
Media > Add New?

**Comment by Mat2012** [comment]
Yes, I can't upload any doc, image, etc. even via Dashboard > Media > Add New
All I have is a "frozen" page :
![bp-docs-test](https://cloud.githubusercontent.com/assets/1023932/6528534/e751906e-c422-11e4-9590-dd917e345207.png)
I'm gonna create a fresh new WP install, with just WP+BP+BP Docs, just in case, and I'll tell you if the problem is still there.

**Comment by boonebgorges** [comment]
If you're having problems on the Dashboard, it means that you likely 
have permissions issues. Make sure that your webserver has permission to 
write to wp-content/uploads.

**Comment by Mat2012** [comment]
Gorges, the problem was not related with permissions.

So, for the record (sorry for my bad english):
I couldnt upload any file since the acivation of BPDocs. When BuddyDocs was turned off, I could normally upload an image or a document in a post or a page. But, once BuddyDocs was activated, I could not upload images and docs no more.

My local install (MAMP) : 
- WordPress 4.1.1
- BP 2.2.1 and BuddyPress docs 1.8.5
- only BP and BP-Docs installed, no other plugin.

I've applied the patch : https://github.com/boonebgorges/buddypress-docs/commit/1744e1fbf127885b1830cd46416e98d9a951f627 (See my thread https://github.com/boonebgorges/buddypress-docs/issues/446 compat. with BP_Group_Extension)

Now, everything works again.

Thank you Gorges, and thanks again for all your work. I'm a big fan.

**Comment by boonebgorges** [comment]
Je vous remercie pour le reportage :)
