### ISSUE TITLE
BuddyPress Docs Front End Edit Error

### ISSUE THREAD

**Issue by LarryWSimpson** [boonebgorges/buddypress-docs#451]
Today I updated all of my plugins to the latest version. Everything on my site seems to work well except the frontend edit tab in my BuddyPress Docs.

My Problem :

When I go into the Edit Tab on the frontend editor, the user interface interactivity doesn't work. For instance, the Associated Group, Access, Tags, and Parent accordions, and the Hide Details link don't work.  Everything is working under the Read and History Tabs. It's like the Java Script or CSS isn't working properly on the frontend editor tab.

Could you give me some guidance on how best to troubleshoot and fix this problem?

Thanks,

Larry Simpson

**Comment by boonebgorges** [comment]
Please open your JavaScript console to see if you're getting any errors 
there.

**Comment by johappel** [comment]
I got an similar error. May be this helps:

Error: Syntax error, unrecognized expression: #[object HTMLDivElement]

in Line 201 in includes/templatetags-edit.php

jQuery('#' + ed.editorContainer) ... throws an error 

maybe there is an problem with the table plugin

Additionally I got a Notice:
Deprecated TinyMCE API call: <target>.onClick.add(..)


Thank you for your great work. buddypress docs ist one of the very best tool for collaborative learning.

**Comment by boonebgorges** [comment]
Thanks for the info, @johappel - Can you specify which vesion of BuddyPress Docs you're using? The fix for this problem should have been in https://github.com/boonebgorges/buddypress-docs/commit/e076a2fe4d2eda969e31a394edd85293af05f493 and part of the 1.8.6 release. See #449.

**Comment by johappel** [comment]
Thank you very much @boonebgorges 
I used release: 1.8.5
So I will look forward for the next 1.8.6 release.

**Comment by boonebgorges** [comment]
Great, thanks!

**Comment by johappel** [comment]
I did a short test with 1.8.6 release. There was only one error, that happen when I click on the table button. 3 javascript errors where thrown in the firebug console, you can see it here: http://gyazo.com/0660bb3116734fdc9afb5d36205f19fe . After that an empty and not closeable dialog window appears in modal. In my opinion the table feature is nice to have, but not essential.
