### ISSUE TITLE
Specifying number of characters shown in summary of doc content in Docs Directory

### ISSUE THREAD

**Issue by nickharambee** [boonebgorges/buddypress-docs#452]
Hi Boone,

Is there a way to specify the number of characters shown in the summary of doc content in the Docs Directory?

Thanks,

Nick

**Comment by dcavins** [comment]
You can specify the number of words shown via the BuddyPress Docs settings panel (`/wp-admin/edit.php?post_type=bp_doc&page=bp-docs-settings`). If you want to specify something else, you could hook into WordPress's `excerpt_length`.

**Comment by nickharambee** [comment]
Hi David,

Thanks - for some reason setting the Directory Excerpt Length to 0 removes all words (which is the expected behaviour I think) but if I set it to any other number the length is always the same, about 40 words.  Any idea why this might be happening?

Nick

**Comment by dcavins** [comment]
Something else is filtering the `excerpt_length` value after BP Docs, I'd guess. You can see all the filters attached to a hook like this: http://wordpress.stackexchange.com/questions/35076/how-can-i-see-all-the-actions-attached-to-an-add-action-hook

In your case, you'll need to add this snippet to a page footer or similar:
```
global $wp_filter;
var_dump( $wp_filter['excerpt_length'] );
```

Lots of plugins filter this value, and one of them is being a bit greedy, in your case.
