### ISSUE TITLE
Pagination links are malformed on group and user directories

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#465]
The pagination links created on user and group directories point to the main docs directory, like so:
http://awesomefizz.local/docs/page/2/

When they should be
http://awesomefizz.local/groups/hush/docs/page/2/ (for the group "hush")
and 
http://awesomefizz.local/members/admin/docs/started/page/2/ (for the user "admin")
or 
http://awesomefizz.local/members/admin/docs/edited/page/3/ (for the user "admin")

**Comment by dcavins** [comment]
See https://github.com/dcavins/buddypress-docs/commits/user-group-dir-pagination for a working solution.

**Comment by boonebgorges** [comment]
Fix looks good, but I'm perplexed how this would've gone unnoticed and 
unfixed for so long.

**Comment by dcavins** [comment]
I know. I'm amazed, stunned, that this was the first I've heard of it. Although, there have been complaints about pagination, I just thought they were entirely the conflicting `per_page` arguments. 

What's your favorite way to clean up a local commit history before committing the changes for real?

**Comment by boonebgorges** [comment]
By "clean up" do you mean you want to combine multiple changesets into 
one? Something like:

$ git checkout 1.9.x
$ git rebase -i my-topic-branch

Then use the interactive rebase tool to sort out changesets.

**Comment by dcavins** [comment]
Right. By "clean up" I mean organize the change sets to put the changes in
a sensible order and remove missteps that I solved two commits later. :)

I'll give the interactive rebase tool a try.

Thanks!

**Comment by dcavins** [comment]
See https://github.com/boonebgorges/buddypress-docs/commit/8753606eff9f16f7d086df0164ce86deff0c02ff
https://github.com/boonebgorges/buddypress-docs/commit/ce486891805448430e168d8e7efdd668ce0050a2
https://github.com/boonebgorges/buddypress-docs/commit/63dfb086d736c9a05280123a3fb7038bd93f457a
https://github.com/boonebgorges/buddypress-docs/commit/0c74b2997e1015ee8dd68cc542568d65ad687b54

for applied fixes.
