### ISSUE TITLE
Docs in different groups with identical `post_name`

### ISSUE THREAD

**Issue by christianwach** [boonebgorges/buddypress-docs#467]
Hi Boone, I've encountered this twice on a client's server but cannot seem to reproduce locally... that two BP Docs posted into different groups with the same `post_title` end up with the same `post_name`. This gets confusing (obviously!) since people can only ever view the one published first. It does not seem to be a race condition since the docs are published days apart.

I thought it might be that doc edits explicitly use `wp_unique_post_slug()` while new docs do not, but it seems that `wp_insert_post()` uses `wp_unique_post_slug()` internally anyway. Any ideas where I should begin looking for possible causes for this?

**Comment by boonebgorges** [comment]
Hm. Just looking at the code, I'd say that what's happening is this. The 
bp_doc post type is registered as 'hierarchical=true'. When creating a 
new doc, includes/query-builder.php uses wp_unique_post_slug(). But that 
function works differently for hierarchical post types: slugs can be 
duplicated as long as they're in different hierarchy trees.

So the first thing I'd test is to see whether the docs are in different 
trees - ie whether they have different values for post_parent.

**Comment by christianwach** [comment]
Thanks @boonebgorges that's exactly what's happened. What's confusing matters is that the two docs still share the same permalink despite one being assigned as a child of another doc. Shouldn't the permalink change for the child doc so it includes the `post_name` of the parent doc in the same way that it does for hierarchical pages? The down side of this is that it could result in some very long URLs if the tree gets deep or the doc `post_name`s are themselves lengthy (which I've noticed they can be) though this would be no different to standard pages, I suppose.

**Comment by boonebgorges** [comment]
I guess it means either that (a) bp_doc items shouldn't be allowed to 
share slugs even though they're a hierarchical taxonomy (ie, some sort 
of filter on wp_unique_post_slug) or (b) bp_doc permalinks should 
reflect their hierarchy (ie, a new rewrite rule).

(a) is probably easier, but it won't account for existing content, so I 
guess (b) is probably going to have to be the answer.

**Comment by cmonjeau** [comment]
Hey,

I've the same issue. Do you have any solutions to avoid this problem?

Thanks,

**Comment by boonebgorges** [comment]
Adding another rewrite rule turned out to be more work than I wanted to take on, so I instead did the `wp_unique_post_slug()` trick. This ensures that new Docs always have unique post slugs, even across hierarchies.

This won't fix existing Docs, but those can be fixed manually in the Dashboard by giving them unique slugs.
