### ISSUE TITLE
Allow filtering of tags cell in docs loop table.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#468]
Hi Boone-

At the moment, there's no way to filter the output of the tags cell in the docs loop table. I know you're exploring retiring the docs loop table, so I don't know if it would be useful to add a filter at this point or not.

I've added the filter here: https://github.com/dcavins/buddypress-docs/commit/f21043ecd0706006a58cffe834c101123ebee721

Let me know if I should commit, edit and commit, or hold off for now.

Thanks!

-David

**Comment by boonebgorges** [comment]
It's OK with me to add it, but yeah, it won't be relevant anymore after 
the tables are no longer the default layout. Perhaps you could write a 
docblock for the new filter, and this limitation could be mentioned in it.

**Comment by dcavins** [comment]
If the new layout is imminent, I'll just hold off for now. Let's just make sure that the new tags output is filterable. :)
