### ISSUE TITLE
bp_docs_is_docs_component() improvements

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#470]
Hi Boone-

`bp_docs_is_docs_component()`: 
```php
/**
 * Is this the BP Docs component?
 */
function bp_docs_is_docs_component() {
	$retval = false;

	$p = get_queried_object();

	if ( is_post_type_archive( bp_docs_get_post_type_name() ) ) {
		$retval = true;
	} else if ( isset( $p->post_type ) && bp_docs_get_post_type_name() == $p->post_type ) {
		$retval = true;
	} else if ( bp_is_current_component( bp_docs_get_docs_slug() ) ) {
		// This covers cases where we're looking at the Docs component of a user
		$retval = true;
	}

	return $retval;
}
```

checks:
1. Are we on the post type archive, probably at `mysite/docs`?
2. Is this a single post that also happens to be a doc?
3. Is this the user's docs library?

I think we could also add a check whether this is a groups docs library, `bp_is_current_action( bp_docs_get_docs_slug() )`. Would that be useful?

**Comment by boonebgorges** [comment]
Sure, update at will. (This is clearly an old function that hasn't been 
touched in a long time.) Just make sure you degrade gracefully if the 
Groups component is disabled.

**Comment by dcavins** [comment]
I was thinking that using `bp_is_current_action()` which ends up querying `buddypress()->action_variables` wouldn't rely on groups being activated. Is that right?

Thanks!

**Comment by boonebgorges** [comment]
You should double-check, but I don't think `bp_is_current_action( 
'groups' )` is reliable if you've changed the slug of the Groups 
component WP page.

**Comment by dcavins** [comment]
Oh, I see your concern. On a group docs library page, this is BP thinks is going on:
```php
Array
(
    [action] => docs
    [slug] => group-slug
    [status] => private
)
```

I was going to hunt that action, not whether we're in a group. I'm nosing around to see where else "docs" might be an action.

**Comment by dcavins** [comment]
Fixed in commit https://github.com/boonebgorges/buddypress-docs/commit/750e2f2cdaf6a10b7a38bec0e8e3152b1e0a9d86.
