### ISSUE TITLE
BP Docs Text Entry Issue

### ISSUE THREAD

**Issue by mkgold** [boonebgorges/buddypress-docs#473]
Boone -- I am working with colleagues at Lane Community College -- they have set up a CBOX site for an NEH institute for doing DH at community colleges here - https://dhatthecc.lanecc.edu/

The person who set up the site, Anne, just experienced a problem and showed it to me on her computer (a PC) using Firefox. When she creates a wiki doc, she can enter text in the title field, but she found that typing text into the main text entry box (in visual or text mode) did nothing.

I figured out that the text _was_ being entered, but that it was being entered as white or gray text so that it was impossible to see in her browser.

I tried starting a doc on my computer (a Mac) in Chrome and experienced the same thing. Screenshots attached -- one showing the text entered but not selected (and so invisible) and one with the text selected so that you can see it's actually there.

![screen shot 2015-07-14 at 4 02 03 pm](https://cloud.githubusercontent.com/assets/278503/8687104/c4c3c7d0-2a41-11e5-9cd3-4a96cf1d949d.png)
![screen shot 2015-07-14 at 4 01 53 pm](https://cloud.githubusercontent.com/assets/278503/8687105/c4c66346-2a41-11e5-9b3e-9638398a9f88.png)

**Comment by boonebgorges** [comment]
Thanks for the report. This is not a general BuddyPress Docs problem, and in fact doesn't seem to be a problem specific to cbox-theme, as I'm not able to reproduce it in any environment that I've got handy.

Are you able to use your browser's developer tools to see what's making the text white?

**Comment by dcavins** [comment]
Boone, I've seen something like this in the wp-admin post editor instance of TinyMCE. It was caused by a javascript problem that was preventing TinyMCE from loading completely. Once I tracked down the js problem and fixed it (caused by another plugin), the text appeared as expected.

If this user can open a console tab of some browser's dev tools, maybe the JavaScript errors would make themselves known.

**Comment by mkgold** [comment]
Sorry to have to ask this, but I'm not sure how to use developer's tools to find the errors on the page . . . is there a resource you can point me to or a quick suggestion you might have for finding the error?

**Comment by boonebgorges** [comment]
Chrome: 
http://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome

Open the console, then refresh the page. Take note of any 
errors/warnings you see, and post them here.

**Comment by dcavins** [comment]
No problem. Here are guides:

Chrome: https://developer.chrome.com/devtools/docs/console
Firefox: https://developer.mozilla.org/en-US/docs/Tools/Web_Console

**Comment by mkgold** [comment]
Thanks to you both. Attached is what I am seeing.

![screen shot 2015-07-15 at 10 44 46 am](https://cloud.githubusercontent.com/assets/278503/8705457/9b0f4c78-2ade-11e5-96dc-bf8afb5e9368.png)

**Comment by dcavins** [comment]
My users were seeing that problem on the wp-admin post editor because of a problem in BP's `mentions.js` file (https://buddypress.trac.wordpress.org/ticket/6487). I doubt that would be applied to the docs instance of the wp-editor, but the result was exactly the same.

**Comment by boonebgorges** [comment]
Thanks, @mkgold. I'm at a bit of a loss to guess at the cause of the problem. 

Can you check to see whether the "Disable the visual editor when writing" option is checked at wp-admin/profile.php? Try toggling it to see if it fixes the problem.

View the source of the page and look for a string containing `tinyMCEPreInit`. Did you find it? If so, paste it here. Where was it - in the footer, or the header?

**Comment by dcavins** [comment]
Does the visual/text editor work on the regular post edit page in `wp-admin`?

**Comment by dcavins** [comment]
I recently had a similar problem to this on the post editor (again) and was reminded that the cause was that this file doesn't respond reliably on my server (which is pretty weird):
wp-includes/js/tinymce/wp-tinymce.php?c=1&ver=4208-20151113

The very awkward fix for me is to change these lines in `wp-includes/class-wp-editor.php`:
`
if ( $compressed ) {
    echo "<script type='text/javascript' src='{$baseurl}/wp-tinymce.php?c=1&amp;$version'></script>\n";
} else {
    echo "<script type='text/javascript' src='{$baseurl}/tinymce{$mce_suffix}.js?$version'></script>\n";
    echo "<script type='text/javascript' src='{$baseurl}/plugins/compat3x/plugin{$suffix}.js?$version'></script>\n";
}
`
to 
`
if ( false ) {
    echo "<script type='text/javascript' src='{$baseurl}/wp-tinymce.php?c=1&amp;$version'></script>\n";
} else {
    echo "<script type='text/javascript' src='{$baseurl}/tinymce{$mce_suffix}.js?$version'></script>\n";
    echo "<script type='text/javascript' src='{$baseurl}/plugins/compat3x/plugin{$suffix}.js?$version'></script>\n";
}
`
so that WP doesn't try to use `wp-tinymce.php` as an intermediary but calls the files directly. I don't know if that will help you, but it's a possibility.

**Comment by boonebgorges** [comment]
Closing this one due to lack of activity, but please report back if you figure out any more connections to Docs or any workarounds.
