### ISSUE TITLE
Only last document showing in directory and all document pages blank

### ISSUE THREAD

**Issue by nickharambee** [boonebgorges/buddypress-docs#474]
Hi Boone,

I recently updated to 1.85 and I am now experiencing issues with BP docs on my site.  Everything looks fine in admin (114 Docs are listed), but only the last document is showing on the directory on the front end of the site, and and when I click on the link to this Doc the page is blank,

So far I have tried deactivating all plugins other than BP and BP Docs and switching to the default BP theme, but still I am experiencing the same issues.  You can see what I mean if you visit this page:

http://soteriabrighton.co.uk/docs/

Any ideas what I can do to get BP Docs working again?

Thanks,

Nick

**Comment by boonebgorges** [comment]
It looks like you're getting a fatal error of some sort. Check your 
error logs or enable WP_DEBUG to see what it is.

**Comment by nickharambee** [comment]
Thanks Boone.  I am seeing the following fatal error:

Fatal error: Call to undefined function wp_revisions_enabled() in /home/admin/domains/soteriabrighton.co.uk/public_html/wp-content/plugins/buddypress-docs/includes/addon-history.php on line 187

**Comment by dcavins** [comment]
What version on WordPress are you running?

**Comment by nickharambee** [comment]
Thanks. That was the issue - I needed to update my version of WP.  Not sure how I missed that.  Apologies!

**Comment by boonebgorges** [comment]
No apologies necessary - thanks for reporting!
