### ISSUE TITLE
Improve memory usage in docs access protection.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#475]
Hi Boone-

I've been doing some optimizations and have been thinking about `BP_Docs_Access_Query->get_doc_ids()` that finds all the docs that the user shouldn't see in order to exclude them from the main query. In order to find the forbidden fruit IDs for logged-out users, the function uses `get_posts()` then `wp_list_pluck()`. I thought I'd try using `WP_Query` directly (in order to have access to the `fields` argument). Memory usage has improved significantly on my testing site--a 40% improvement.

I know there are some caveats with using `WP_Query`, so I'd appreciate your feedback on this, to make sure I'm not walking into a morass. I did mimic the way that `get_posts()` uses `WP_Query` to minimize the change. Although I don't really get the subtleties between the following:
```php
$var = new WP_Query( $args );
```
and 

```php
$wpq = new WP_Query();
$var = $wpq->query( $args );
``` 
If you can explain, I'd love to know.

See https://github.com/dcavins/buddypress-docs/commit/ce3cebbd829c15f9e8a5c56afbaeb0fcd0ad4bcb 

Thanks!

-David

**Comment by boonebgorges** [comment]
Yeah, `fields=ids` is a great improvement. If I didn't do it that way originally, it's because I didn't know what I was doing :) Go for it.

As for the "subtleties", there are none :) If you call `new WP_Query()` with non-empty `$args`, it calls `$this->query( $args )`. So your two examples are functionally identical - the first one is just one line shorter.

**Comment by dcavins** [comment]
Thanks for the feedback, Boone. I've merged the changes. What's that thing about not knowing what you're doing? "Not all who wander are totally incompetent" or something like that. :)
