### ISSUE TITLE
Improve ability to alter output/behavior of the docs loop info header.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#476]
Hi Boone-

In adding an extra taxonomy to use with BP Docs, I realized that I needed a bit more flexibility in the info header on the docs loop. The way that the current code is written for the "You are viewing the term: sailboats - View All Docs" message is too specific about creating the url for the link "View All Docs." I also wanted to have one of the drawers open by default, so added a filter on the toggle title class so that plugins can modify which toggle link is marked as active.

See changes in last two commits here: https://github.com/dcavins/buddypress-docs/commits/info_header_behavior

Thanks!

-David

**Comment by boonebgorges** [comment]
Sure, these look like good changes. Go for it :)

**Comment by dcavins** [comment]
Thanks for your feedback. I've merged the changes.
