### ISSUE TITLE
"add files" button not working

### ISSUE THREAD

**Issue by ahm-3d** [boonebgorges/buddypress-docs#477]
Hi,
i am using:
buddypress docs v.1.8.6
buddypress  v.2.3.2.1
wordpress v.4.2.3
the "add files" button not working

**Comment by boonebgorges** [comment]
Can you please give more details about "not working"? What are you 
doing, and what do you see? Do you see any errors in your browser's 
JavaScript console?

**Comment by ahm-3d** [comment]
the error i am getting in the console is _initJQuery() is not defined when i am on this page http://xxxxxxxx.com/resources/create/
i see the form where you can create a resource, however the add files button doesnt open up the media popup.
this works fine when i am on localhost but not when it is live

**Comment by boonebgorges** [comment]
Thanks for the additional details. One possibility is that you're running a plugin or a theme that is loading TinyMCE at some point early on the page, before BuddyPress Docs loads its scripts. Do you have any other plugins that are loading TinyMCE instances on the same page? In buddypress-docs/includes/component.php, find the line that looks like this:

    	add_action( 'wp_enqueue_scripts',       array( $this, 'enqueue_scripts' 	) );

and change it to

    	add_action( 'wp_enqueue_scripts',       array( $this, 'enqueue_scripts' 	), 5 );

to see if that makes a difference.

**Comment by ahm-3d** [comment]
that didnt work.
i seem to be getting a different behavior between localhost and live. localhost is loading /plugins/buddypress-docs/includes/js/attachments.js in the footer while in my live version it is not loading that script at all on the page

**Comment by boonebgorges** [comment]
Who is your webhost? Is it, by chance, WP Engine?

**Comment by ahm-3d** [comment]
wow, that is a very good guess, yes it is wpengine and i am trying to use the plugin within the staging area

**Comment by boonebgorges** [comment]
Aha! I had an inkling. Check out this thread https://wordpress.org/support/topic/add-files-not-working?replies=17, especially starting here https://wordpress.org/support/topic/add-files-not-working?replies=17#post-6165053. It's possible that you'll have to contact your host to lift the "no heartbeat on the front end" restriction.

**Comment by ahm-3d** [comment]
thanks. i contacted wpengine and asked them to "turn off the heartbeat option as advised here https://wordpress.org/support/topic/add-files-not-working?replies=17". once they have done that, it took me few refreshes to see that plugin is working again :-D
many thanks for your continuous support.

**Comment by boonebgorges** [comment]
Excellent! Thanks for working with me on this one.

**Comment by dcavins** [comment]
Closing, but we need to remember the WP Engine bit.
