### ISSUE TITLE
Danish language file corrupt?

### ISSUE THREAD

**Issue by lektoren** [boonebgorges/buddypress-docs#480]
Hi, please have a look at the included Danish language files.

The translations are OK, but the words/letters are somehow displayed wrong.

Thanks, 

Lars

**Comment by boonebgorges** [comment]
Thanks for letting me know about this. I don't speak Danish :) but it does look like the current .mo file is somehow corrupt.

Could you download this file https://github.com/boonebgorges/buddypress-docs/blob/1.8.x/languages/bp-docs-da_DK.mo (click the "Raw" button) and replace your existing da_DK.mo file with it? Let me know if that solves the problem for you.

**Comment by lektoren** [comment]
Yup, that fixed the problem.
Thanks again!

Lars

**Comment by boonebgorges** [comment]
Great, thanks!
