### ISSUE TITLE
Targeting the docs create screen via CSS is hard.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#484]
Hi Boone-

We've got an edit body class but no create screen body class, which could be useful if you're trying to simplify the create screen only, for instance. See https://github.com/dcavins/buddypress-docs/commit/cdca00f3f1f6795b632fa80a33f6bce73a2f2a1e for a simple fix.

Let me know if this class name suits you, or if you have any general objections.

-David

**Comment by boonebgorges** [comment]
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FPfIyB2QJmLOAU%2F200.gif&f=1

**Comment by dcavins** [comment]
A GIF is worth at least three words. :)
