### ISSUE TITLE
Non-admins can't associate new Docs with groups

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#485]
Stems from 6e3b3c25c. It appears that using a real post type means that the `current_user_can( 'bp_docs_manage' )` check is failing.

**Comment by dcavins** [comment]
Is this fixing the same problem that https://github.com/boonebgorges/buddypress-docs/commit/f20958b2b43ba58387affca4079ce2999f5fbf84 was fixing? (The "Associated Group" and "Access" meta boxes weren't being output on the create screen.)

Does that mean that the earlier fix didn't work for you?

**Comment by boonebgorges** [comment]
Dammit. I searched the repo because I was sure this had been addressed, 
but didn't find it on Github, and I hadn't pulled down this commit, 
apparently.

It does look like your fix is fine. I don't think what I've added will 
hurt anything, so I'm going to leave it, unless you have objections.

**Comment by dcavins** [comment]
Nope, I just wanted to make sure that the earlier fix actually did something and deserved to exist. :)
