### ISSUE TITLE
Permissions needed to create document and set permissions/associated groups

### ISSUE THREAD

**Issue by nightyx** [boonebgorges/buddypress-docs#486]
Hey guys,
I have a rather strange bug. When creating a new document as an admin everything is fine, I can create text, add attachements, set access, tags and the associated group. When I try the same with a user having the subscriber role the layout is broken in terms of, i cant set the associated group and access AND additionally the comments of another document are listed below the create new docs form.
So it looks to me like this is a problem of user permissions. Question is: which specific permissions does the user need? Other predefined levels like author, editor, contributor have the same broken layout.
Then I went ahead and created a new wordpress installation, installing just BuddyPress & bbPress & BuddyPress Docs. Still a normal user cannot change associated group/permissions. But gladly the other comments weren't visible. So regarding permissions/associated group I guess I have to hook to some permission method to auto set it in my guess; could you point me the point where I can connect to?
The broken layout can be fixed through reinstalling the other platform. No idea whats the cause for this.

**Comment by dcavins** [comment]
Hi @nightyx-

Thanks for the bug report. This is a known issue that's been fixed in this change set:
https://github.com/boonebgorges/buddypress-docs/commit/f20958b2b43ba58387affca4079ce2999f5fbf84 

Let us know if this doesn't address your problem.

-David

**Comment by nightyx** [comment]
Hola @dcavins 
that works like a charm; and also thanks for the very quick reply, much appreciated.
One additional question: Can you point me in the right direction to write some filters/actions to set the associated group always to be the current one and also to set the access to members of that group automatically? That would be very nice

Kind regards
Olli

PS: Since we solved the original issue, I´ll close this ticket

**Comment by dcavins** [comment]
Hi @nightyx-

"set the associated group always to be the current one and also to set the access to members of that group automatically"

This should be the default behavior if a user clicks on "Create Doc" from a group's doc library. If it isn't, there could be a JavaScript conflict (or something else is broken). Please open your browser's console to make sure that there's not a JS breakage.

Best,

-David
