### ISSUE TITLE
Improve redirect after delete

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#489]
After deleting a document, the user is dropped to the main docs directory. It would be better if they dropped back to the most recent docs directory they were viewing (user library, a group library).

One ugh-inducing way to do this would be to create a session cookie that stores the last docs library viewed. (Would love to find a more clever way to do it.)

**Comment by boonebgorges** [comment]
> One ugh-inducing way to do this would be to create a session cookie that
 > stores the last docs library viewed. (Would love to find a more clever
 > way to do it.)

You could store a hidden input on single docs that contains this 
information. Also a nightmare, especially when navigating around a lot. 
A cookie is probably the appropriate way to do it.

**Comment by r-a-y** [comment]
I would say check the referer and parse it to see what page you were on, then you can determine where the redirect should go.

This only works if the referer isn't stripped via a browser setting or addon.

**Comment by boonebgorges** [comment]
But the deletion may not take place on the pageload immediately after 
leaving a directory. It might go like this: directory -> single Doc read 
mode -> single Doc edit mode. So the referer wouldn't have the necessary 
information.

**Comment by dcavins** [comment]
Boone, do you have any good ideas about how to write a test for this? I guess I could use `goto()`s and check the cookie value, but it seems kind of gross.

Also, as to the value stored in the cookie, what makes sense, the actual url of the directory: 
`http://www.docsrule.org/members/doclover/docs`
or some generalized value that we can use to later calculate the target:
`user: 22` or `site` or `group: 11`
or some other cleverer option?

**Comment by boonebgorges** [comment]
I wouldn't bother attempting to write PHPUnit tests for this. If we had behavior tests, that'd be the appropriate place for them. (Ask me sometime about how I once spent an afternoon adding Selenium + Behat to buddypress-docs.) (Actually, don't.)

**Comment by boonebgorges** [comment]
As for the cookie value, I'd go with the simplest method, which is to store the URI. The redirectc itself should probably use `wp_safe_redirect()` to skirt security concerns.

**Comment by dcavins** [comment]
Hi Boone-

Please have a look at this change set: https://github.com/dcavins/buddypress-docs/commit/1ab18f1c9e365e5d2211dfb021e50ff93063d885

The patch creates/updates a session cookie tracking the most recently visited docs directory and uses that value for the post-delete redirect. We were using `bp_core_redirect`, which uses `wp_safe_redirect()` internally, so I left that in place.

The cookie setting part could be made more sophisticated and check for an existing, matching cookie value before resetting the value of the cookie, if you think there'd be a performance advantage.

Thanks!

**Comment by boonebgorges** [comment]
A couple thoughts:

- We need to make sure that we're setting cookies before any other headers are sent to the browser. `bp_ready` seems riskily late. Can we do something like `bp_actions`?
- What's up with the weird hook priorities? 36, 37, 38
- `bp_docs_is_group_docs()` needs a check to make sure that bp-groups is active (or put the function in integration-groups.php instead)

Otherwise the technique looks OK to me.

**Comment by dcavins** [comment]
Thanks for your feedback. Yes, `bp_ready` is pretty late. I was wrestling action points and priorities (hence the weird 36, 37 and 38 priorities) when using another hook. `bp_actions` sounds better. I'll try it.

I'd like `bp_docs_is_group_docs()` to be available all the time, so I'd rather leave it outside of the class (those status functions are useful to me pretty often) if that suits you. I'll add the `is_active()` check. I'm neutral on whether it belongs in `integration-groups.php` or near the other status checks, though, so would appreciate it if you'd decide.

Thanks again!

**Comment by boonebgorges** [comment]
> I'd like bp_docs_is_group_docs() to be available all the time, so I'd rather leave it outside of the class (those status functions are useful to me pretty often) if that suits you

OK, that's fine. Just make sure there's some sort of check to avoid fatals. `bp_is_active()` should be good.

**Comment by dcavins** [comment]
Thanks for your comments, @boonebgorges. I've refreshed the commit here: https://github.com/dcavins/buddypress-docs/commit/1a8ac713cab8e357e0d26ed2a66d71e9f4a34027

On a separate note, there are a few other instances of `bp_is_group()` that exist outside of `integration-groups.php`. Should I go ahead and run a pre-check on those as well in another patch?

**Comment by boonebgorges** [comment]
Looks great, @dcavins. One more minor suggestion is that you may want to 
suppress errors on calls to setcookie(); if another plugin is 
incorrectly sending headers early, it'll result in errors.

Please feel free to add the function_exists() or bp_is_active() checks 
where you'd like.

**Comment by dcavins** [comment]
Thanks for taking the time to look it over. Are you imagining error suppresion à la `@setcookie()`? That seems like good self-defense; is that a good general plan for `setcookie()` in WP plugins, given WP's plugin architecture?

**Comment by boonebgorges** [comment]
Yes, I was thinking @setcookie(). I think it's a decent idea in WP 
plugins, especially if you're firing fairly late (like we do, at 'wp').

**Comment by dcavins** [comment]
OK, will update and commit. Thanks again.

**Comment by dcavins** [comment]
Resolved in 1.8 branch: https://github.com/boonebgorges/buddypress-docs/commit/a073a2a0572c5740fbb2f5a439b6a5ec784781d6
Resolved in 1.9 branch: https://github.com/boonebgorges/buddypress-docs/commit/3f11c2f90c4b35dfdd8bb7f52c6d3b7cdd140efb
