### ISSUE TITLE
bp_docs_is_docs_enabled_for_group() always true if docs disabled again

### ISSUE THREAD

**Issue by wdfee** [boonebgorges/buddypress-docs#492]
Hi Boone,
if docs have been enabled inside a group and disabled again `bp_docs_is_docs_enabled_for_group()` returns true. In integration-groups.php 1464-1465 `isset( $group_settings['group-enable'] )`returns true, because it is set to 0 (zero). Just change to `!empty( $group_settings['group-enable'] )`.
Thanks (and sorry for still not being able to make pull requests...), Fee

**Comment by boonebgorges** [comment]
Good call! Thanks for the report.
