### ISSUE TITLE
Doc access issues on IIS 8.5

### ISSUE THREAD

**Issue by github-trh** [boonebgorges/buddypress-docs#493]
I am receiving the following error when trying to open an attached file to a newly created doc:
HTTP Error 500.50 - URL Rewrite Module Error.  PDF, DOC, XLS file types have been tested with same results - I cannot open the file that was just attached.  This is a local install on 2012R2 windows server and I am attempting to set up a local intranet using latest CBOX and BP with CBOX theme.  No other plugins are installed aside from those that are part of the CBOX install.
I have attempted to modify the web.config file based on the IIS 7 suggestion given here (https://github.com/boonebgorges/buddypress-docs/wiki/Attachment-Privacy) , but with no luck. I have tested within a group and not in a group.  Any suggestions would be great, I love this plug-in and would love to use it!

**Comment by dcavins** [comment]
Hi github-trh-

I also have used IIS, and it doesn't always see eye-to-eye with WordPress, but it can be made to work. (OK, well, I've never used 8.5, so I'll leave myself some leeway there.)

Do WordPress pretty permalinks work on your site?

Can you verify that the file is being attached to the right place? (It should end up in `/wp-content/uploads/bp-attachments/{doc_id}`.)

Can you share any non-sensitive parts of your `web.config`?

**Comment by github-trh** [comment]
Well, that was actually my first challenge, to get the links working.  They seemed to work once I created the web.config file and added this rewrite rule I found elsewhere:
<configuration>
  <system.webServer>
    <rewrite>
		<rules>
			<rule name="Main Rule" patternSyntax="ECMAScript" stopProcessing="true">
				<match url=".*" />
				<conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
				</conditions>
				<action type="Rewrite" url="test/index.php" appendQueryString="true" />
                    <serverVariables>
                    </serverVariables>
		</rules>
	</rewrite>
    </system.webServer>
</configuration>

However, if I add a rule between the above rewrite containers as suggested in the II7 article, I get a 500.19 error (not well formed xml...) page pointing to the "<action type="Redirect" url="?p={R:1}&bp-attachment={R:2}"/> " part of the suggested code.

**Comment by github-trh** [comment]
I just re-read the IIS7 paragraph (https://github.com/boonebgorges/buddypress-docs/wiki/Attachment-Privacy) and realized that this rule PREVENTS access, which is the opposite of what I am wanting to do.
I wonder if editing the rule in some way would allow access to doc attachments, fixing my problem...

**Comment by boonebgorges** [comment]
Is this a multisite installation? Are the uploaded files at `wp-content/uploads/bp-attachments/`, or `wp-content/blogs.dir/x/files/bp-attachments` (where `x` is a blog ID)?

**Comment by github-trh** [comment]
Not a multisite installation.  Just created a single "test" site before formally launching a company intranet.  Everything is to remain within these walls on this site, so I am not concerned about SEO, etc.
Files are located at wp-content/uploads/bp-attachments.  A new folder within bp-attachments is created at each doc attachment attempt (numerical) that I make.

**Comment by boonebgorges** [comment]
So when you click on an attachment link, what URL is it attempting to 
load? Is it of the form 
example.com/test/uploads/bp-attachments/123/file.jpg?

**Comment by github-trh** [comment]
Exactly, see below:

![capture3](https://cloud.githubusercontent.com/assets/15528543/10886533/0c25bf90-8148-11e5-8729-defcf403488d.JPG)

**Comment by boonebgorges** [comment]
Hm. The thing about the "rewrite" error is that, as far as I can see, 
this file should not require a rewrite: the physical file exists at the 
path described.

I have a feeling that the `isFile` check in your main Rewrite rule is 
being applied too generally. It'd be appropriate for Multisite (at 
least, for versions of Multisite that expect to write their content 
through ms-blogs.php), but on non-Multisite, uploads ought to be served 
directly by the webserver.

Maybe it's worth a try commenting that line out? If that doesn't work, 
you might try removing the entire rewrite block, and then seeing whether 
the attachment will load. I know that this will break pretty permalinks, 
but it would at least help to narrow down the issue.

**Comment by github-trh** [comment]
Ok, thanks for the suggestion Boone.  I'll give it a shot in a few hours.

**Comment by github-trh** [comment]
I played around with the rewrite rule in several different ways.  First, I removed the entire ‘IsFile’ line.  The page looked to be without any styling but I was still able to get to the wm.jpg file in order to test the doc attachment ability and the results were the same (500.50 URL Rewrite Module Error...).  I uploaded a frsh attachment and same results.  I also made a few other changes to the re-write rule just to see what would happen, but with no success. I even created another web.config file and located it at the bp-attachments level…again, no luck.
If I remove the re-write rule entirely, I’m back to square one where I am unable to navigate to Group, Members, Docs, etc.  Therefore, I am unable to test the doc attachment.

![c4](https://cloud.githubusercontent.com/assets/15528543/10890103/b44d885c-815b-11e5-8938-85a694d51e4d.png)

I did some digging through your bp docs folder and noticed a file called “attachments.php”.  Is there something in this file (or maybe elsewhere) where the permissions of a file are altered during the attachment process?  I find that when I navigate to the file that was uploaded, I am unable to open it.  Prior to the attachment effort, it opened just fine.

**Comment by boonebgorges** [comment]
> Therefore, I am unable to test the doc attachment.

With the rewrite rule enabled, go to the page with the list of attachments. Copy the URL of an attachment (or load it in another tab). Then remove the rewrite rule, and attempt to visit/reload that URL.

> I find that when I navigate to the file that was uploaded, I am unable to open it. Prior to the attachment effort, it opened just fine.

As far as I can see, the file is not the issue. The problem is that IIS is refusing to serve the file. This is also unrelated to any permissions issues in Docs. 

Another thing to test: Try uploading an attachment to a WordPress post. Are you able to access it?

**Comment by github-trh** [comment]
Ok, thanks.  I will try those tests....One more thing to add - when I go into the folder structure and replace the file that will not open with the same exact file before it went through the doc attachment process, I am able to open/view the file successfully through the website as intended.

**Comment by boonebgorges** [comment]
Ah, this is a helpful piece of information.

@dcavins Is it possible that IIS is setting the file permissions on the 
upload incorrectly? I know absolutely nothing about it.

**Comment by github-trh** [comment]
Boone - I performed the test you described (...Then remove the rewrite rule, and attempt to visit/reload that URL).
After disabling the rule I reloaded the tab and instead of an error it gave me loads of this jibberish:

![c5](https://cloud.githubusercontent.com/assets/15528543/10890812/d0b9d820-815f-11e5-9de6-799b587440c7.JPG)

I re-enable the rule and it's back to the 500.50 URL Rewrite Module Error page.

**Comment by dcavins** [comment]
My working WP/BP/BP Docs `web.config` file looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
        <rules>
            <clear />
            <rule name="wordpress" patternSyntax="Wildcard">
                <match url="*" />
                <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                </conditions>
                <action type="Rewrite" url="index.php" />
            </rule>
        </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

It's simpler than yours, maybe try it out and see if it works with your server setup.

**Comment by github-trh** [comment]
Thanks dcavins, that is much cleaner.  I copied it exactly and placed it actually inside my site folder.  I also placed the web.config file directly in the buddypress-docs folder.
However, my doc attachments problem still exists.  I tried creating a new doc with a new attachment and still no luck.  I went into the file where the new folder was created and it must have something to do with permissions when uploading.  Here is what I see when viewing properties of newly attached file (that I cannot access on the web browser side):

![c6](https://cloud.githubusercontent.com/assets/15528543/10897108/fa785c58-8183-11e5-8550-24e2febd386a.JPG)

**Comment by github-trh** [comment]
I can override permissions in folders and all the way down to the actual bp-attachments folder so anyone can do whatever (full control), but once I go through the process of attaching a file to a doc, which triggers a new numerical folder to be created with the file inside, it does not adhere to the permissions of the other folders.  Extremely frustrating, I feel like I'm so close to resolving this.

**Comment by github-trh** [comment]
@boonebgorges - I deactivated my BP Docs plugin and installed a sub par doc management plugin (SP Project & Document Mgr) to do some testing.  With that plugin, files are uploaded and placed in a single folder (wwwroot\test\wp-content\uploads\sp-client-document-manager\1) and they open on the front end just fine.  I already gave full reign to users in my folders, so this test just tells me that permissions are fine and there is nothing on the IIS end I could do to get BP Docs to work as well.  At some point, the plugin created a folder called "1" and files that are uploaded are able to be read just fine.
Not sure where to go from here on this, I just wanted to share the latest.  I really wish the BP Docs would work since it obviously integrates best with my BP setup.  Feel free to close this one unless you have any final recommendations.  Thank for the help, it is greatly appreciated.

**Comment by boonebgorges** [comment]
@github-trh Thanks for the update.

> this test just tells me that permissions are fine and there is nothing on the IIS end I could do to get BP Docs to work as well

That seems a bit broad. It seems pretty clear to me that *something* could be done, it's just that the people on this thread don't know enough about IIS to make it work.

Docs uses WP's core libraries to handle uploads. Indeed, Docs doesn't do much at all with respect to uploading - the core media library does it all, and Docs only tells WP to put the files in a specific directory. There's clearly something happening with the way the combination of Docs and IIS is creating the directory that's the problem. If it were linux, I'd say it make have to do with umask. But I'm not sure where to go from here. At some point, I may try to spin up an IIS8 instance to test myself, but unfortunately this is non-trivial to do.

Sorry I can't be more of a help. I'll leave the ticket open for now, in case an intrepid IIS sysadmin drops by.

**Comment by github-trh** [comment]
@boonebgorges  Ok, sounds good.  Thanks again for offering solutions, I know this is not a typical BP use (intranet on Windows server) so I figured there would be a few bumps in the road.

**Comment by github-trh** [comment]
Here is the solution that fixes this problem:
First, I had to locate the PHP.ini file (https://www.ostraining.com/blog/coding/phpini-file/)
Second, edit the text under "File Uploads" specifying where the temporary directory is located.  With nothing entered, it was going to the system default which was messing with the permissions of the file when it went this route.  I created a temp folder at my own specified location for this action to take place so that file uploads do not inherit wrong permissions.  Also make the location change under the [WebPIChanges] section...basically anywhere it identifies the "upload_tmp_dir" and points it to the system.

**Comment by dcavins** [comment]
Ah, yes, if you leave the system temp directory defaults in place, it causes a whole host of problems (php doesn't have permission to empty the default temp directory). So it would make sense that this would be another. Ugh!

Thanks for the update!
