### ISSUE TITLE
Add filter to control inclusion of "parent doc" settings section.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#494]
In cases where there are a lot of BP Docs, the “parent doc” section gets unwieldy for some users, like site admins.

See https://github.com/dcavins/buddypress-docs/commit/20ba553db3c811510ae0b37e4473b8fca89f7528

**Comment by boonebgorges** [comment]
Sure, this is fine with me. 

Longer term, we might consider a more lightweight way to load stuff here. Like maybe we preload a certain number, and then load the rest via JS. See https://core.trac.wordpress.org/ticket/19867 for a related issue.

**Comment by dcavins** [comment]
Yes, I agree that dropdowns don't scale well. We could treat this like a bp-suggestions input maybe instead of a dropdown. Or maybe use a dropdown for under a certain number of possible docs and switch to a search over that threshold.
