### ISSUE TITLE
Translations not working for component.php

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#495]
With BP Docs v1.8.8 the strings in component.php ("Doc successfully removed from the group" etc.) are not localized in the frontend. The translations are available in my po/mo files but don't show up...

**Comment by boonebgorges** [comment]
Are you using the de-DE files shipped with the plugin? I don't see the strings listed there. (The last update to that file appears to be 2013-05-27.)

**Comment by schwarzaufweiss** [comment]
I've updated the de_DE files I provided a long time ago from your actual pot. That's why these strings are now included in my translations. Hopefully I will find the time to supply new de_DE files including the backend strings etc. in the near future.

**Comment by boonebgorges** [comment]
In that case I'm not sure. I tried a fr_FR translation (with the strings 
added) and they showed up as expected.

Can you send me a copy of your po/mo files so that I can test locally?
