### ISSUE TITLE
Empty trash in frontend

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#496]
Hi Boone,
please provide a link in /members/username/docs/ to delete the trash (function in the frontend to delete a members doc trash).

**Comment by boonebgorges** [comment]
Good idea, thanks.

**Comment by dcavins** [comment]
I've been thinking about adding a doc action link "permanently delete this doc" to delete docs on a per-doc basis. Taking the "empty all trashed docs" approach is interesting. Though it seems like we'd need to add a "trash" view (and probably still have a way to delete docs individually). Not that that's a bad idea, but it does add more elements/states to the UI.

**Comment by schwarzaufweiss** [comment]
Personally I don't see a need to add a trash view. For me it's good enough that the files are flaged with "Trash". Anyway, it doesn't help much for some users if deleted Docs are on separate pages (depending on the wp setting for no of posts). I would simply include a link "Empty trash" to permanently delete the flaged files – eventually only the files that are visible on the page I'm looking at. OK, that way the trash is not really empty…

**Comment by dcavins** [comment]
I created a patch that adds the mechanism for permanently deleting a doc. The way it works as written is that anyone who can manage the doc can put the doc in the trash (as currently done).
![doc-trash-button](https://cloud.githubusercontent.com/assets/1391994/11989375/b2aafd84-a9c1-11e5-98f2-fb30230ef9bb.png)

Then, the doc's owner or a site admin can either untrash the doc or permanently delete it. (Once it's gone, it's really gone.) Trashed docs only appear in a user's doc library.
![doc-perm-delete-button](https://cloud.githubusercontent.com/assets/1391994/11989382/cc456478-a9c1-11e5-975c-5318fe351e2f.png)

The patch is here: https://github.com/dcavins/buddypress-docs/commit/9affd05a039425fe13b85e7ff75ad8b7e2b0bfa4 

Comments welcome.

**Comment by schwarzaufweiss** [comment]
Thanks! Merry xmas!

**Comment by dcavins** [comment]
Boone, I'd like to include this functionality in 1.9.0. I remember that there was something about this that you were unsure of, but I can't find that email or GH issue comment. The two patches are:

Allow doc owners to permanently delete an item:
https://github.com/boonebgorges/buddypress-docs/commit/9affd05a039425fe13b85e7ff75ad8b7e2b0bfa4

Allow doc owners and site admins to delete in one step:
https://github.com/boonebgorges/buddypress-docs/commit/625bde108e6c29febe0c3e2580c6448fbc7bc889

(I've no idea why those commits look like they're part of your repo and not my fork.)

**Comment by boonebgorges** [comment]
Sure, go for it. I don't remember the reasons against :)

**Comment by dcavins** [comment]
Well, if you remember what your comment was, let's fix it so that everyone's happy.

Fixed in https://github.com/boonebgorges/buddypress-docs/commit/d7e6450efd1de91edabe55249034c219d10e4921 and https://github.com/boonebgorges/buddypress-docs/commit/9df122ff1ca4b7b114f4b4e1bebc7a1d0aab5cb8.
