### ISSUE TITLE
Doc created by one user cannot be seen in directory by other users

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#497]
From a report by @schwarzaufweiss :

> I'm able to reproduce it with two notebooks in the same wifi while having access to the remote server (one Mac and one Windows).
> 
> If one user creates a Doc with default permissions (public), the other one is not able to see it in /docs! If I use two accounts on the same machine with two browsers, it's not a problem. I've installed your latest final release on that server (v1.8.8). Some server info:
> 
> WordPress Version:      4.2.5
> PHP Version:            5.3.10-1ubuntu3.21
> MySQL Version:          5.5.44-0ubuntu0.12.04.1-log
> Web Server:             Apache

**Comment by boonebgorges** [comment]
@schwarzaufweiss For clarification: the users on the separate machines are using the same WP account? (You state that it's working when using separate accounts on the same machine.)

**Comment by schwarzaufweiss** [comment]
No, not the same account. Real world environment with different accounts. Different accounts on one machine with two browsers (no issue), different accounts on two machines in the same wifi (not able to see Docs in /docs).

**Comment by boonebgorges** [comment]
Sorry for not following up on this. My best guess is that there's a cache in between the client computer and WordPress, and the cache wasn't being properly updated for some reason. If you come up with more details on how to reproduce, please feel free to post them here and we can reassess.
