### ISSUE TITLE
Improve testing setup.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#498]
I've had recurring problems with the BP Docs testing setup on my machines. This slight change seems to work better for me. If it works for your testing setup, I'd like to update it so that I don't spend who knows how long tracking down apparently random relative file link problems the next time I want to run some tests. :)

See: https://github.com/dcavins/buddypress-docs/commit/240f1fbd3560de7a094198bd5414bbaf0f5edd6c

**Comment by boonebgorges** [comment]
If it's working for you, be my guest :)

**Comment by dcavins** [comment]
Ha ha does this mean that I represent half of all the people who run tests on BP Docs? :)

**Comment by dcavins** [comment]
Fixed in 1.8.x branch: https://github.com/boonebgorges/buddypress-docs/commit/13c90c3233dd575af3cdce1d008bad812c877ee0

and in 1.9.x branch: https://github.com/boonebgorges/buddypress-docs/commit/5050717079bfca872a3b99cbb9e6814a74bd75fe
