### ISSUE TITLE
"manage" capability is generally not set.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#499]
The manage capability is not usually set in the `bp_docs_settings` post meta. Should it be set? It defaults to "creator" if not set, which may be the only sensible value at the moment.

(Is this a bug?)

**Comment by boonebgorges** [comment]
It's a bug if it's causing problems :) Do you need the ability for this 
to be customizable?

**Comment by dcavins** [comment]
Nope, the default behavior is fine, I was just digging into what `bp_docs_manage` actually means while working on some permanent deletion handling:

https://github.com/dcavins/buddypress-docs/commits/perm-delete-action

First I built it so that it'd be a two-step process so that while a few people might be able to trash it, only the creator or a site admin could really make it go away permanently. Then once I realized that "manage" means the creator or a site admin, I wondered if I was making it too many steps. Anyway, the most current commit allows the doc manager to choose whether to trash it or delete it permanently. Trashing is great for mutually-managed docs, but at some point they do have to go away. :)

If you have thoughts on reasonably non-annoying workflows or on the UI (this is a lot of options) I'd like to hear them.

Happy new year!

**Comment by boonebgorges** [comment]
If this is about permanent  deletion, my personal inclination is to do nothing :) Normal users shouldn't ever really need anything other than Trash. And if an admin is concerned about storage space (or whatever), the trash can be emptied from wp-admin. 

I would definitely say that there should not be a direct path from publish -> delete; as in the Dashboard, the Delete Permanently UI should only show up for items that are already in the trash.

I have no idea how this would play nicely with `bp_docs_manage` :) It seems to me that deletion (as opposed to trashing) is a site-maintenance task more than a doc-specific-maintenance task. So it's not clear to me how to map doc-specific permissions onto deletion. Maybe you could build a plugin first? :)

**Comment by dcavins** [comment]
> I would definitely say that there should not be a direct path from publish -> delete

This suits me. Site admins can always permanently delete docs from the wp-admin dashboard. And with the next-to-last commit in the above branch, users can permanently delete individual items that are already in the trash.

In either case, it would play OK with `bp_docs_manage` because that only is true for doc creators and users with the `bp_moderate` capability (// Only users that can 'manage_options' on this site can 'bp_moderate'). I think that's right, anyway. :)
