### ISSUE TITLE
Scope CSS selectors

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#500]
Some of our CSS selectors are a bit too vanilla, like `.description`, and affect elements on the page beyond the BP Docs content. See https://wordpress.org/support/topic/italic-font-style-aapears-but-not-in-css-defined.

**Comment by boonebgorges** [comment]
:+1: Let's tread gently here, because selector changes will break theme-specific styling. But yeah, we should do a better job being specific.

**Comment by dcavins** [comment]
Maybe the new BP Docs container would provide a nice range in which to work.
https://github.com/boonebgorges/buddypress-docs/commit/2318e093f82127d857f834b4d229404cd7c328d1

**Comment by dcavins** [comment]
Fixed in https://github.com/boonebgorges/buddypress-docs/commit/8f3b0ecea38def761e35bc8fafd161309495c618.
