### ISSUE TITLE
allow more file types to be uploaded

### ISSUE THREAD

**Issue by armenu** [boonebgorges/buddypress-docs#501]
I'm new to Wordpress and Buddypress. I have the buddypress-docs plugin installed. Our site has a number of private groups that upload a lot of files to the Docs area. When we try to upload files (clicking on "Add Files") with certain extensions (examples: .pub, .ttf) an error message opens saying that the file type is prohibited from being uploaded. Can the types of files that can be uploaded be expanded in some way?

**Comment by dcavins** [comment]
Hi Armenu-

BuddyPress Docs respects the file types specified in WordPress. 
https://codex.wordpress.org/Uploading_Files

You can pretty easily expand the allowed types. If you're using multisite, you just go update the setting: https://premium.wpmudev.org/blog/how-to-change-the-allowed-file-upload-types-in-wordpress-multisite/

If you're using single site, you can add a filter to a plugin:
http://www.paulund.co.uk/change-wordpress-upload-mime-types

You can find a pretty extensive mime type list here:
http://www.freeformatter.com/mime-types-list.html

Note that your host may have extra restrictions on what file types are allowed.
