### ISSUE TITLE
Page layout for documents saved

### ISSUE THREAD

**Issue by nientedafare** [boonebgorges/buddypress-docs#503]
Hello, thank you for your work, it is extremely useful. I noticed that the document saved, unlike the archive of documents and the creation of a new document, use the layout of each post instead of page layout. I have a theme that uses different layouts for pages and posts: how can I attribute to the individual document the layout of the pages?

**Comment by boonebgorges** [comment]
Hi there - Individual Docs are WordPress custom post types, which means that they use whatever "single template" is available. On some themes, this is page.php; on some themes, it's single.php. You can override this with a customized template, by copying your desired template file to a file called `single-bp_doc.php` in your theme directory.

**Comment by nientedafare** [comment]
Thank you for your reply. I learned something new on Wordpress. Unfortunately, your suggestion doesn't solve the problem. I use a theme that allows to customize the sidebars ( Hueman Theme by nikeo ). Is it possible to assign to saved documents only the page layout as for new documents instead whatever single template is available?

**Comment by dcavins** [comment]
In taking a quick look at how "Hueman" is constructed, my best guess is to make a copy of the `page.php` file and save it named as @boonebgorges has suggested above: `single-bp_doc.php`. If that doesn't work, it might be worth asking the theme author if he or she has an idea of the best way to create a new page-like template for a particular custom post type. (The theme's doing some custom things that are a little unusual.)

**Comment by nientedafare** [comment]
Thank both of you for your kindness. I will put this question to the author of theme. This plugin is excellent, I use it in a community of activists: it is very useful!
