### ISSUE TITLE
Add "Recent Docs" Widget

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#506]
On the support forums, a request came in for a "Recent Docs" widget, which I'm surprised has never come up before. Here's a prototype: https://github.com/dcavins/buddypress-docs/commit/5491d30e84a35ebc8e291a5bb30e6b4d89b7bd23

`bp_docs_has_docs` worked well for this because of its sensible defaults when used on groups and user profile. Please take a look at how I faked a `wp_reset_postdata()` here: https://github.com/dcavins/buddypress-docs/commit/5491d30e84a35ebc8e291a5bb30e6b4d89b7bd23#diff-7c2dfbe563d7d00a90f217d61496140eR64
and here: https://github.com/dcavins/buddypress-docs/commit/5491d30e84a35ebc8e291a5bb30e6b4d89b7bd23#diff-7c2dfbe563d7d00a90f217d61496140eR115
to see if that seems reasonable.

**Comment by boonebgorges** [comment]
This technique looks good to me :+1:

**Comment by dcavins** [comment]
Are you OK with adding this widget to the plugin? (It could easily be made into a plugin.)

**Comment by boonebgorges** [comment]
Add away!
