### ISSUE TITLE
Folders: JS update_new_folder_selectors_for_group shouldn't run at page load on manage folders screen.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#508]
Running at page load on a single doc's edit screen works fine, but when this function runs on a group's "manage folders" screen, it blows up because the associated group id isn't set.

See https://github.com/dcavins/buddypress-docs/commit/ddbccf5eab8ce3ae2be98de8c94164e2ab07bef0 in which I <3 JS and testing for the existence of values.

Is there a better way, or some other way to scope these functions altogether by body class or similar?

**Comment by boonebgorges** [comment]
D'oh. This technique looks fine.

**Comment by dcavins** [comment]
Fixed in https://github.com/boonebgorges/buddypress-docs/commit/5cfcb9146ef3b5da993172f2d053a775ed496eb4
