### ISSUE TITLE
Make the "up one folder" link click target larger

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#515]
At the moment, the "up one folder" link target is the text: ..

We could give that link a minimum size or change the text to say "go up one folder" or something so there's a bigger click target.

**Comment by boonebgorges** [comment]
I'd prefer to force the link to be larger using CSS. The '..' text is, I 
think, pretty standard UX for folder structures. For better 
accessibility, we could add a .screen-reader-text span.

**Comment by dcavins** [comment]
I think we're both used to seeing '..' because we use Unix. :) Windows uses an up arrow, and both Mac and Windows use a "back" button. Windows also features the breadcrumbs as a navigational aid, and they're available in OS X, but you have to turn that view on (it's off by default).

Happily, the browser has a back button, and you've already built the breadcrumb navigation, so I think those bases are covered. 

This changeset enlarges the click area and adds the screen reader text, which is a great idea:https://github.com/dcavins/buddypress-docs/commit/ae07d14e98932c4d97b32ba2bd09eee0e898063f

**Comment by boonebgorges** [comment]
Looks good.

**Comment by dcavins** [comment]
Fixed in https://github.com/boonebgorges/buddypress-docs/commit/9749de67d87c4c579e4a836e4a3b5417cfb3e050
