### ISSUE TITLE
Prepare for wordpress.org translation

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#523]
BuddyPress Docs currently ships with all of its translations, stored in the `/languages/` directory. This is extra overhead for the plugin, and extra overhead for the plugin maintainers and translators, who must manage translations via Github. Let's move to wordpress.org for translations.

There are a few hurdles, similar to those outlined here: https://github.com/boonebgorges/buddypress-group-email-subscription/issues/80#issue-137627834

**Comment by dcavins** [comment]
If this also means that translations will be stored in `wp-content/languages`, this would be nice for people who have custom translations and currently lose their po/mo files every time they update the plugin.

**Comment by McCage** [comment]
Same here; I would like to have a dutch translation and already had a discussion on https://wordpress.org/support/topic/advanced-settings-4/#post-9092792 
Loco is a nice plugin to make and adapt custom translations and keep them over updates:
https://wordpress.org/plugins/loco-translate/ displays the same error messages

**Comment by boonebgorges** [comment]
@dcavins Is there more work to do here?

**Comment by boonebgorges** [comment]
It looks like this broke something that I hadn't thought clearly about: overridden theme templates.

I'm going to reach out to the authors of Boss, which should fix the issue for a large number of sites. Not sure there's much else that we can do for custom themes, but let's keep the solution in mind in case more reports roll in.

**Comment by dcavins** [comment]
That's unfortunate. (I knew that custom templates would break, but I didn't
realize that Boss includes a set of templates for BP Docs.)
