### ISSUE TITLE
This plugin is not properly prepared for localization

### ISSUE THREAD

**Issue by slaFFik** [boonebgorges/buddypress-docs#528]
Would be nice to have all translations on translate.wordpress.org

`This plugin is not properly prepared for localization. If you would like to translate this plugin, please contact the author.`

See here: https://translate.wordpress.org/projects/wp-plugins/buddypress-docs

I would definitely help with translating it into ru_RU (current translation is outdated)

**Comment by dcavins** [comment]
Thanks, @slaFFik, @boonebgorges opened a ticket about translations a few days ago, too, so it must be time to do it.
Related: https://github.com/boonebgorges/buddypress-docs/issues/523

**Comment by boonebgorges** [comment]
Closing in favor of #523.
