### ISSUE TITLE
Hyperlinks in docs

### ISSUE THREAD

**Issue by armenu** [boonebgorges/buddypress-docs#534]
I've been using Docs extensively with several Buddypress groups. Just now I created a doc and pasted in a link to a web page. When I did the same with a message I posted to the group, the link became live and one could click on it to go to the web page. But this did not happen when I put the link in the body of the doc. It is not a clickable link. Users will have to copy and paste it in their web browsers. Can live hyperlinks be added as a feature to Buddypress Docs?

**Comment by dcavins** [comment]
Hi Armenu-

You can add this line to your theme's `functions.php` to make this so:

`add_filter( 'bp_docs_get_the_content', 'make_clickable' );`

(`make_clickable()` is a WP function https://codex.wordpress.org/Function_Reference/make_clickable.)

It does seem like expected behavior, so maybe we should add it to the plugin. In any case, you can enable it tonight. :)

**Comment by armenu** [comment]
Hi David,

Not knowing php language and never having done anything with the 
functions.php file I had some trepidation about how to follow your 
directions. I just added the code you sent me to the bottom of the file 
and was amazed that was all it took. I am always amazed when something 
that I fear will be too complicated for me to do turns out to be simply 
done.

Thank you!

Arthur

P.S. I can't tell you how happy being able to sort docs into groups has 
made all the members of our groups.

David Cavins wrote:
> Hi Armenu-
>
> You can add this line to your theme's |functions.php| to make this so:
>
> |add_filter( 'bp_docs_get_the_content', 'make_clickable' );|
>
> (|make_clickable()| is a WP function
> https://codex.wordpress.org/Function_Reference/make_clickable.)
>
> It does seem like expected behavior, so maybe we should add it to the
> plugin. In any case, you can enable it tonight. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/boonebgorges/buddypress-docs/issues/534#issuecomment-201688184>
>

-- 
Arthur Menu, Sidney, British Columbia, Canada

**Comment by dcavins** [comment]
Glad it worked out for you!

I'm also glad to hear that the new folders feature is useful for your members. We're pretty excited about it, too.
