### ISSUE TITLE
Folder metabox fields should only show when necessary

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#538]
- If there are no existing folders, don't show the "existing folder" radio button
- If there are no existing folders, don't show the "Parent" option

**Comment by boonebgorges** [comment]
This is turning out to be harder than expected. Will have to it in JS to work with AJAX for changing associated group.

**Comment by boonebgorges** [comment]
Spent some more time futzing with this, and it's more work than I can fit in.

**Comment by dcavins** [comment]
I see what you mean. This is going to have to be done more like the access levels, when group association is mixed in.
