### ISSUE TITLE
File types

### ISSUE THREAD

**Issue by github-trh** [boonebgorges/buddypress-docs#539]
Is there a way to expand on the possible file types a user can attach?

**Comment by boonebgorges** [comment]
Hello there - Currently, Docs does not do any specific filtering of file types. This means that Docs inherits whatever your WP settings are. In Multisite, there's a UI to change this (Network Admin > Settings); I don't think there's a UI for it in non-MS. You can use the `upload_mimes` filter to whitelist file types beyond what WP allows by default. See http://www.wpdownloadmanager.com/using-upload_mimes-to-allow-upload-and-download-of-unrecognized-mime-type/ for a good tutorial.

I'll leave this ticket open, as I think it could be a good enhancement to build a wrapper that would allow the whitelist to be filtered in the Docs context only, and maybe even a UI for the purpose.

**Comment by github-trh** [comment]
Thanks Boone, that worked!  Users will need to right-click/save as since it gives me the 404 error in a new tab, but at least the filter allows the file type to get uploaded.

**Comment by boonebgorges** [comment]
Cool!
