### ISSUE TITLE
de_DE language pack update

### ISSUE THREAD

**Issue by svendue** [boonebgorges/buddypress-docs#544]
Hi everyone,

is there an update for de_DE language pack? 

The old one is 3 years old. I updated myself but it didn't work with the new version.

Thanks for help and advises

**Comment by dcavins** [comment]
Hi @svendue!

Thanks for your message, and many thanks for volunteering to update the de_DE language pack.

In the pull request you opened, I'm not seeing the files `bp-docs-de_DE.mo` & `bp-docs-de_DE.po` listed among the changes. 

Can you attach your updated files to this issue instead?

Thanks!

-David

**Comment by svendue** [comment]
Is attached ti the pull request.

**Comment by svendue** [comment]
Do you have it?
[de_DE.zip](https://github.com/boonebgorges/buddypress-docs/files/330592/de_DE.zip)
