### ISSUE TITLE
Panel Open and Close Links Don't Work

### ISSUE THREAD

**Issue by LarryWSimpson** [boonebgorges/buddypress-docs#546]
I'm working on a Wordpress Site which will be an online community for those interested in the management of business process improvement initiatives. I want to use BuddyPress Docs for members to create content that will eventually be used for content marketing to help build their personal and business brands. I can create a new Doc with no problems, but I'm having a problem with the features available when editing existing Docs.

Briefly, the problem is, in edit and create mode all links to toggle the containers opened and closed do not work. They just cause the page to scroll to the top, with no effect on the container panels.  When clicking one of these links the following is returned /docs/sop-introduction/edit/#. And, edit mode opens with all of the panels closed, so there is no way to edit the settings.

I'm not sure if this is a javascript or other problem. I can give you access to a page with this problem for troubleshooting if that would help. Please let me know how to best help you identify the problem.

Thanks,

Larry

**Comment by dcavins** [comment]
Hi Larry- 

That's classic "JavaScript is broken" behavior. Try using the console in Chrome (https://developer.chrome.com/devtools/docs/console) or Firefox (https://developer.mozilla.org/en-US/docs/Tools/Web_Console) on the docs edit screen, and let us know what error is being reported.

Best,

-David

**Comment by LarryWSimpson** [comment]
Here are the outputs from the console when a BP Docs page opens in Chrome. These are only warnings, no errors.

JQMIGRATE: Migrate is installed, version 1.4.1
:formatted:497'Performance.webkitClearResourceTimings' is deprecated. Please use 'Performance.clearResourceTimings' instead.

util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

I also tried all of the related suggestions in the WordPress support forum, but nothing fixed the problem.

BP Docs is a critical element of my Website, so I am committed for the long term in helping you find the cause of the problem. I have all of the other components of my Website working. BP Docs is the only feature that I need to fix.

I could setup an account for you so that you could investigate the problem yourself. That would probably be the best way for you to isolate the problem.

Let me know what to do next.

Thanks for your help.

Larry

**Comment by dcavins** [comment]
Hi Larry. Please create an account for me. Send the credential to d_cavins76 at yahoo dot com.

**Comment by dcavins** [comment]
Hi Larry-

Which hosting company do you use to host your web site?

**Comment by LarryWSimpson** [comment]
I sent the information you requested to the Email you gave above.

Let me know if you find the problem.

Thanks, Larry

**Comment by dcavins** [comment]
Hi Larry-

I received your email, but didn't have a chance to look today. (BP 2.6.1 happened today.)

-David

**Comment by LarryWSimpson** [comment]
That's ok. No hurry. I like the dynamic javascript features in BP Docs and I hope you can get them fixed  within the plugin. However, consider other options also, like moving the BP Docs javascript files to a different location in my WordPress site, so that they don conflict with other plugins, or changing the CSS so that all dialogs are always expanded and the links that are used for data entry work without the javascript.

Thanks for your help.

Larry

**Comment by dcavins** [comment]
Thanks to Larry for solving the issue: https://wordpress.org/support/topic/add-files-button-not-working-even-after-wp-453

which was a conflict with WP Engine's customized handling of `heartbeat_autosave_only`.
