### ISSUE TITLE
BuddyPress Docs share with one member.

### ISSUE THREAD

**Issue by skanthemore** [boonebgorges/buddypress-docs#548]
Hello,

Is it possible to share files between two users privately using Buddypres Docs?

I know I can do it through missateges but is not what I'm interested. I need private communication between user and admin and files.

Thank you,
Best regards

**Comment by dcavins** [comment]
Hi Skanthemore-

It's not possible to share a doc between any two users using BP Docs--the privacy settings are based around logged-in members and members of a specific group.

**Comment by skanthemore** [comment]
Thanks for the response,

but what about this comment,
https://wordpress.org/plugins/buddypress-docs/

> "Docs that can be linked to groups **or users,** with a variety of privacy levels"

**Comment by dcavins** [comment]
If you have a test BuddyPress site, you should just try it out. Docs can be associated with users or groups, with a variety of privacy options. If the doc is not associated with a group (so it's associated with a user), you can set access to anyone, logged in or doc owner only. If it's associated with a group, you can choose anyone, logged in, group member, or group admins or mods.

**Comment by skanthemore** [comment]
Hello,

very clear,
thank you for the explanation,

What I need is something to send DOCS between admin and every single user,
I will try BuddyDrive,

Best regards ;)

**Comment by dcavins** [comment]
I suppose one way you could use BP Docs to do that is to have each user set the doc access to "doc author only." Site admins have access to all docs, so they'd still be able to see the docs. But it's not an obvious way to get there.

**Comment by skanthemore** [comment]
Another way might be to create a specific group for each user. It works, but is not very practical if you do not manage to automate when creating a new user.

I will try your way anyway ;)

Thanks again,
