### ISSUE TITLE
Hint needed with manage-folders template

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#550]
The manage-folders template does show up while using BP Docs 1.9.1 with a default WP theme, but I'm still not able to do it with the premium theme I'm using. With that theme I have to register templates in functions.php like this …

`$bp_docs_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/single-doc.php";
register_context( 'BuddyPress Docs Create', 'bp_docs_create', $bp_docs_template);

$bp_docs_edit_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/edit-doc.php";
register_context( 'BuddyPress Docs Edit', 'bp_docs_edit', $bp_docs_edit_template);

$bp_docs_single_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/single-bp_doc.php";
register_context( 'BuddyPress Docs Single', 'bp_docs_single', $bp_docs_single_template);

$bp_docs_archive_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/archive-bp_doc.php";
register_context( 'BuddyPress Docs Index', 'bp_docs_index', $bp_docs_archive_template);

$bp_docs_folders_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/manage-folders.php";
register_context( 'BuddyPress Docs Folders', 'bp_docs_folders', $bp_docs_folders_template);
`

bp_docs_folders (last line of code) and all other params I tried based on my search in bp docs source are not working. What do I have to use to show up the manage-folders template? Thanks for help, Hans

**Comment by dcavins** [comment]
Hi there-

The manage folders template is called from the `docs-loop.php` template:
https://github.com/boonebgorges/buddypress-docs/blob/1.9.x/includes/templates/docs/docs-loop.php#L11

I imagine that to make the manage folders interface show up, you'll have to ensure that the up-to-date version of `docs-loop.php` is being loaded (not being overridden by the theme you're using). Does your premium theme specifically include templates for BP Docs? If so, you could change the theme to refer to the new template until they have a chance to catch up.

Best,

-David

**Comment by schwarzaufweiss** [comment]
Hi @dcavins 

Thanks for your reply. The theme I'm using does NOT include templates for BP Docs. I have to register the templates that are included in the plugin in functions.php of the theme.

I now tried it with these lines …
<pre>
$bp_docs_folders_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/docs-loop.php";
register_context( 'BuddyPress Docs Folders', 'bp_docs_folders', $bp_docs_folders_template);</pre>
…and also this way:
<pre>
$bp_docs_folders_template = WP_PLUGIN_DIR . "/buddypress-docs/includes/templates/docs/docs-loop.php";
register_context( 'BuddyPress Docs Folders', 'bp_docs_manage_folders', $bp_docs_folders_template);
</pre>
…but I'm still not able to show the manage-folders UI with that theme.

Do you have any idea what params I should put in functions.php?

Thanks,
Hans

**Comment by dcavins** [comment]
Honestly, I've never used a theme that didn't use the standard WP template hierarchy (because it's so important to BuddyPress working well). Have you tried asking the theme authors for advice?

If it were me troubleshooting, I'd add some echo statements to `docs-loop`, like 
`<?php if ( current_user_can( 'bp_docs_manage_folders' ) && bp_docs_is_folder_manage_view() ) : ?>
        <?php echo 'user can manage docs and is folder manage view'; ?>
	<?php bp_locate_template( 'docs/manage-folders.php', true ) ?>
<?php else : ?>`

and in `manage-folders.php` at the very top:
<?php echo `manage-folders has been called`; ?>

Then at least you'll know if the template loader is even trying to run.

**Comment by schwarzaufweiss** [comment]
Thanks again. The theme is called "Salutation" and my site is www.lerngruppen.net – I will never use that theme again. It's always behind the BP cycle, and the theme and the theme author are "not easy to handle"… ;-)

**Comment by schwarzaufweiss** [comment]
…in the meantime, Brajesh Singh was so kind to help me. We had to copy the /docs folder with manage-folders.php to the theme folder (no changes in functions.php). It's working now. Thanks @dcavins for your advice.
