### ISSUE TITLE
Create Document Link Not Working

### ISSUE THREAD

**Issue by CannabisProphet** [boonebgorges/buddypress-docs#559]
I can not get the create document link to work in my frofile or groups. It seems the only way to create a document is to add it through the backend or click the "NEW" dropdown menu in the browser and then click doc which then takes you to the backend to post. Have done something wrong or not set it up right?

It takes you to an archive page
![page-shot-2016-12-10 docs forcannabis us](https://cloud.githubusercontent.com/assets/12688464/21072097/e0910056-be7c-11e6-9d23-f0de6e2bfcb9.png)

**Comment by boonebgorges** [comment]
Can you say more about exactly how the link doesn't work? Do you see the 
link at all? When you click it, what happens?

- Do you get a totally white screen? If so, enable WP_DEBUG or check 
your error log
- Does nothing happen at all? If so, check your browser console.
- Or perhaps you're able to visit the New Doc page, but are unable to 
*save* the new document?

**Comment by CannabisProphet** [comment]
The link is there but when you click on it, it takes you to an archive page where you can see recent created documents but it dont appear to have any way to create a document. All I see is in the screen shot I provided in the original post.

**Comment by dcavins** [comment]
Hi there-

A couple of questions: 

- What is the target (href) in the "Create Document" link? In my installation, the "create" link from my profile points to `http://bptest.local/docs/create/` and from a group it points to `http://bptest.local/docs/create/?group={group-slug}`.

- When you follow the link, does your browser show that as the window's location, or is it being rewritten to just `http://bptest.local/docs`?

**Comment by CannabisProphet** [comment]
/docs/create/

**Comment by dcavins** [comment]
OK, so the link is being created correctly. When you click the button, do you end up at `/docs/create/`, or just `/docs/`?
