### ISSUE TITLE
Create document only for certain roles

### ISSUE THREAD

**Issue by peerv** [boonebgorges/buddypress-docs#560]
I don't want all users of my site to Create Documents.
Now anybody can Create Documents even when not being a member of a group.
I have set the "Minimum role to associate Docs with this group" to " Group member"
I would expect that none group members would not be able to create documents.
I new to this plugin, maybe I have some misunderstanding! 

What I want to achieve is  to hide the "Create Document" button based on the users role?

Thanks for the advice
Peter

**Comment by dcavins** [comment]
You can filter who can create docs by adding your own callback on the `bp_docs_current_user_can_create_in_context` hook.
https://github.com/boonebgorges/buddypress-docs/blob/master/includes/functions.php#L326

(You can also add a filter to WP's capability system if that's more familiar to you.)

Then, you can make whatever rules you need. If the user can't create a doc, the button will not appear, and the user will not be able to access the create docs page.

**Comment by peerv** [comment]
Thanks for the quick answer. I will take it from here.

**Comment by dcavins** [comment]
👍
