### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by perezsmarie** [boonebgorges/buddypress-docs#561]
My wordpress has updated to the latest version which is 4.7.1 and since this update I'm getting a HTTP Error when uploading files to BuddyPress Docs. However, I don't have this issue using my normal Media Library. Is there a workaround for this?

**Comment by boonebgorges** [comment]
Can you share more information about the error?

**Comment by dcavins** [comment]
Hi perezsmarie-

I'm responding to this question over at the WP forum topic you created: https://wordpress.org/support/topic/http-error-103/
