### ISSUE TITLE
remove_edit_lock triggers to often

### ISSUE THREAD

**Issue by ReneLuecking** [boonebgorges/buddypress-docs#565]
In the bp-docs.js an ajax call with the action **remove_edit_lock** is set to all links (except those with the class _toggle-link_). There should be more exceptions (for example if you open the media uploader).

Maybe a solution will be to use the **unload** event to trigger the ajax call: https://developer.mozilla.org/en-US/docs/Web/Events/unload

**Comment by boonebgorges** [comment]
Thanks for the ticket and for the suggestion. `window.unload` is a much better solution.
