### ISSUE TITLE
Cookie "bp-docs-last-docs-directory" wrong on relative website

### ISSUE THREAD

**Issue by ReneLuecking** [boonebgorges/buddypress-docs#574]
The value of the cookie `bp-docs-last-docs-directory` is created by: `home_url( $_SERVER['REQUEST_URI'] )`. This won't work on websites, where WordPress is installed in a relative path and the home url is something like: `example.com/wordpress`. With this example, all urls which are set by this cookie, have the part "/wordpress" doubled and it results in a "404 not found":
```php
$_SERVER['REQUEST_URI'] = '/wordpress/docs';
home_url() = 'example.com/wordpress';
home_url( $_SERVER['REQUEST_URI'] ) = 'example.com/wordpress/wordpress/docs'; // => 404 not found
```

**Comment by boonebgorges** [comment]
Thanks for the report. It seems like `home_url()` should probably be sufficient, right?

**Comment by ReneLuecking** [comment]
`home_url()` will always return the homepage, if no parameter is committed. You should use

    // PHP solution
    $current_url = '//' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
or

    // WordPress solution
    global $wp;
    $current_url = home_url( $wp->request )
