### ISSUE TITLE
Add filter for attachment query during cache population in bp_docs_has_docs().

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#576]
There's a handy filter for the query args when fetching the attachments for a single doc, but the args used during cache population on directories is not filterable. (As an example, I'm ordering all attachments by title, alphabetically ascending.) 

This commit solves it, but I want to run the new filter name by @boonebgorges  before committing.
https://github.com/dcavins/buddypress-docs/commit/92f8ee80d38d2c624d00b06c1ea4905875b469be

I sort of wanted to use the same filter name as the other instance, but I can imagine a case where a dev would want to include different attachments on the directory vs a single doc, so maybe unique filter names is OK.

**Comment by boonebgorges** [comment]
Having two separate filters seems good to me. Filter name is not beautiful, but it seems like it should be fine. Thanks!

**Comment by dcavins** [comment]
If you have a suggestion for a better filter name, let me know. It's easy to change (before someone might be using it!). :)

**Comment by dcavins** [comment]
This was reolved in b1fc1af.
