### ISSUE TITLE
use BP_DOCS_SLUG for group subnav tab

### ISSUE THREAD

**Issue by wdfee** [boonebgorges/buddypress-docs#580]
Hi Boone,
a very small hint: in templatetags.php line 1549 could you please use `bp_is_current_action( BP_DOCS_SLUG )` instead of `bp_is_current_action( 'docs' )`? The current tab isn't marked if another slug is defined.
Thanks and greetz, Fee

**Comment by boonebgorges** [comment]
Sure thing! It's now in the 1.9.x branch and it'll be part of the next release.
