### ISSUE TITLE
Delete an doc deletes not the attachments 

### ISSUE THREAD

**Issue by staude** [boonebgorges/buddypress-docs#582]
When I delete an doc, the attachments from the doc in the media library are not delete.

**Comment by boonebgorges** [comment]
Howdy - thanks for the report.

What's the default WP behavior here? If you delete a post, are its attachments sent to the trash?

**Comment by staude** [comment]
Hi,

No, when I delete a post, the attachment is still available in the media library. These attachments are also freely accessible. BuddyPress Doc attachments are not freely available, they are linked to the Doc and are displayed in the media library only as broken images. If I delete the doc, I have no possibility to access the attachment. Therefore, it would be logical, that the appendix is deleted together with the Doc.

**Comment by boonebgorges** [comment]
Yeah, I guess that seems right - there's no mechanism for sharing attachments between Docs, so there's no real concern that trashing an attachment would mess up another Doc. We'll look into implementing this.

**Comment by staude** [comment]
Thank you

**Comment by boonebgorges** [comment]
Looking at this more carefully:

> BuddyPress Doc attachments are not freely available, they are linked to the Doc 

This is true in the sense that you can't browse existing attachments when adding new attachments to posts.

> and are displayed in the media library only as broken images.

But this doesn't seem true to me - they show up normally in the media library, from what I can see.

Perhaps I'm being overly conservative, but it seems to me that silently deleting data other than what is being directly deleted could cause problems. If someone wants this behavior, it's pretty easy to implement like this: https://wordpress.stackexchange.com/questions/109793/delete-associated-media-upon-page-deletion For this reason, I'm going to close the ticket.
