### ISSUE TITLE
'There are no docs for this view...' message confusing in nested folders

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#596]
Folders that contain no docs, but contain other folders, get the message: `There are no docs in this context...`. This feels confusing. For a client, I've removed it: the message only shows if the folder (or top-level group context) is *truly* empty - no docs and no folders. @dcavins Do you have an opinion about whether this change makes sense in buddypress-docs itself?

**Comment by dcavins** [comment]
I think that sounds like a good change (showing the message only if the folder/view really has no contents). 👍

**Comment by boonebgorges** [comment]
Cool, let's do it.
