### ISSUE TITLE
Cannot create new document in German translation

### ISSUE THREAD

**Issue by oli-ver** [boonebgorges/buddypress-docs#603]
When activating the German translation of the website users cannot create documents anymore:

![bildschirmfoto 2017-12-26 um 14 46 52](https://user-images.githubusercontent.com/965863/34357950-b7680e44-ea4b-11e7-9d89-2112926349ad.png)

It seems there is a missing " in the span element with id "idle-warning-time":

`
	<div class="doc-content">

	<div id="idle-warning" style="display:none">
		<p>Sie haben für <span id = "idle-warning-time> </ span> Leerlauf</p>
	</div>

	<form action="" method="post" class="standard-form" id="doc-form">
	    <div class="doc-header">
			    </div>
	    <div class="doc-content-wrapper">
		<div id="doc-content-title">
			<label for="doc-title">Titel</label>
			<input type="text" id="doc-title" name="doc[title]" class="long" value="" />
		</div>`

**Comment by dcavins** [comment]
Hi Oliver-

This is a known issue with the German translation. You are exactly correct with your diagnosis.

The easiest fix is to remove the entire div like this: https://github.com/boonebgorges/buddypress-docs/commit/2ba26192d204bf8db4410f2d0e635a56688b1550

Thanks for the report!

-David
