### ISSUE TITLE
Hide the taxonomy UI for internal taxonomies

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#609]
The "Associated Items" taxonomy, which is used for access query efficiency, causes a lot of confusion to people. It would be better if it were out of sight, so that people didn't try to use it.

**Comment by boonebgorges** [comment]
👍 I have meant to do this in the past.

**Comment by dcavins** [comment]
I made this change (https://github.com/dcavins/buddypress-docs/commit/7eba662380a470ee5db8c6b990408a4e145e716b) and haven't seen any issues. Is there more to do?

**Comment by boonebgorges** [comment]
Nope, that looks right to me.

**Comment by dcavins** [comment]
Fixed via https://github.com/boonebgorges/buddypress-docs/commit/8086593d3d020b756929d5c7bf4b81e2afd25ebb.
