### ISSUE TITLE
Add "Access" controls, etc., to doc edit on back end.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#610]
The WP Admin back end causes a lot of confusion for people, generally. If we're going to make docs seem editable from the back end (which they are, within reason), we should probably go ahead and make it fully work.

**Comment by boonebgorges** [comment]
Agreed, but a fairly big job. Maybe a dupe of #118?

**Comment by dcavins** [comment]
Yes, this is a big and unthrilling but at some point necessary job. It'll be a lot easier now that we've made some changes to the doc save mechanism generally.

Closing in favor of #118.
