### ISSUE TITLE
Share document with more than one group 

### ISSUE THREAD

**Issue by Darkool** [boonebgorges/buddypress-docs#614]
Hi there, I would like to know if it's possible share docs with more than 1 group.

Maybe duplicate 1 document on other group or better give permission  to other group(s) to edit or view the same document.

Best regards.

**Comment by boonebgorges** [comment]
Thanks for the ticket, @Darkool! I agree this would be a useful feature.

Some of the technical issues can be found at #443 and #124. The scope of this task is large, which means it likely won't be done in the foreseeable future unless someone is individually motivated or funded to do it.
