### ISSUE TITLE
Create a Doc menu is half page.

### ISSUE THREAD

**Issue by geglynn** [boonebgorges/buddypress-docs#616]
Create a Doc produces a page that is half width.  All other menu items show as full width.  Any suggestions on how I might fix this would be appreciated.
![buddypress-docs-menu](https://user-images.githubusercontent.com/36685652/36461138-0526e1ea-168a-11e8-9280-11d5f93d2720.png)

**Comment by boonebgorges** [comment]
Hi @geglynn - Sorry to hear you're having the issue. It's not possible to tell from your screenshot what's happening. You'll need to use your browser's element inspector (right click, then Inspect Element) to figure out what's happening. Hint: right click and select the "New Doc" header, and then keep hovering over successive parents in the element tree until you find the first one that is half-width. Then click it and find the style that's causing it to be half-width.

**Comment by geglynn** [comment]
Thanks Boone

I have pasted a picture of the element inspector with the offending line highlighted.  When I change the width value from 50 to 100% within the element inspector it renders full screen.  Not being a programmer I so not know how to fix this on the web site and would appreciate any advice you can offer.   I can provide you with a username and password if that would help.

Regards

Graham

**Comment by boonebgorges** [comment]
I can take a look, but it looks like you didn't properly embed the image. Could you try again?

**Comment by geglynn** [comment]
Trying again

**Comment by boonebgorges** [comment]
Hm, don't see it there either. I don't think you can attach an image to an email response - try embedding it in the GitHub web interface.

**Comment by geglynn** [comment]
![inspect element](https://user-images.githubusercontent.com/36685652/36519475-bf61034a-1759-11e8-9038-911baf19349e.jpg)

**Comment by dcavins** [comment]
By looking at https://hellocommunity.net/docs/, I can see that the Opti theme is applying this rule:

```
.archive article, .search article {
    border-bottom: 1px solid #cccccc;
    padding: 20px 20px 4px 20px;
    overflow: hidden;
    float: left;
    width: 49.5%;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    min-height: 6.5em;
}
```
And that `width: 49.5%;` is the issue. You'll have to do some CSS overrides to get the theme to behave.

Something like 
```
.bp-docs.archive article {
    width: 100%;
}
```
Will fix it. You'll have to see whether the theme supports adding arbitrary CSS (they're all different).

**Comment by geglynn** [comment]
David

You are brilliant – that fixed the problem.

Thanks

Graham

**Comment by boonebgorges** [comment]
Thanks to both of you!
