### ISSUE TITLE
`test_comment_as_logged_out_user_success()` failing

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#644]
After 617dfde17.

@dcavins - I'm not 100% sure what the correct behavior here is. It could be that the test needs to be updated?

**Comment by boonebgorges** [comment]
Looking this over again, it appears that it's intended behavior to exclude non-authenticated comments from auto-approval in all cases, even if 'anyone' is the Docs setting. So I'm just going to remove the test. @dcavins If this is wrong, feel free to reopen and adjust.

**Comment by dcavins** [comment]
I agree that logged-out users should not have their comments auto-approved, so that test should be removed. Thanks!
