### ISSUE TITLE
Parent doc option not available in the backend editor

### ISSUE THREAD

**Issue by aparadox** [boonebgorges/buddypress-docs#650]
When adding or editing a buddypress-doc from the Wordpress backend, there is no option to select a parent doc. It works fine from the frontend though. Is that the intended behaviour? 

Environment:
- Wordpress 5.0.3
- Theme: Generate Press 2.2.1
- BuddyPress 4.1.0
- Buddypress-docs 2.1.1

**Comment by boonebgorges** [comment]
Yes, this is more or less expected. The plugin is not designed for the creation and editing of content via the Dashboard; everything should happen through the front-end interface. This may change in the future - see #118.
