### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by petrk94** [boonebgorges/buddypress-docs#656]
Hello,

I would like to know, whether a export or download functionality exist? 
Docx or PDF would be finde.

Thanks

**Comment by boonebgorges** [comment]
Hello - No, this is not currently built into the plugin. For PDF, you could likely use one of the existing PDF export plugins for WordPress: https://wordpress.org/plugins/printfriendly/ is a good example.

See #570 for more.

**Comment by petrk94** [comment]
Okay, how about if I develop that part by myself? 
We need this function in our organization but with the next update it would disappear again.
I checked the database and how its stored and I dont think it should be complicated to export as HTML and than export a PDF or even docx from that.

**Comment by boonebgorges** [comment]
Sure, please feel free to work on it, and I'll be glad to review.

I'll note that it's definitely easy to create HTML, but the step from HTML to PDF or docx is much harder. There are existing libraries and tools, but you'll need to do lots of work to account for the specifics of how HTML documents work (think: text formatting, embedded images, links, etc).
