### ISSUE TITLE
Currently Edited Fatal Error

### ISSUE THREAD

**Issue by alieneila** [boonebgorges/buddypress-docs#663]
I do not have groups activated in BuddyPress...
When an article is being edited by someone else and the "This doc is currently being edited..." message shows, I am also getting...

Fatal error: Uncaught Error: Call to undefined function bp_group_is_admin() in /wp-content/plugins/buddypress-docs/includes/templates/docs/single/index.php:20 Stack trace: #0 /wp-includes/template.php(724): require() #1 /wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(155): load_template('/...', false) #2 /wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(61): bp_locate_template(Array, true, false) #3 /wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(338): bp_get_template_part('docs/single/ind...', NULL) #4 /wp-content/plugins/buddypress-docs/includes/theme-bridge.php(254): bp_buffer_template_part('docs/single/ind...') #5 /wp-includes/class-wp-hook.php(288): BP_Docs_Theme_Compat->sin in /wp-content/plugins/buddypress-docs/includes/templates/docs/single/index.php on line 20

**Comment by boonebgorges** [comment]
Thanks for the report and for the backtrace.. You're correct that this is a bug. Are you able to patch your installation with f68ed26 to confirm that it fixes the issue?

**Comment by alieneila** [comment]
Yup, that fixed it. Thank you =)
