### ISSUE TITLE
Admin Setting - Default Doc Settings

### ISSUE THREAD

**Issue by alieneila** [boonebgorges/buddypress-docs#664]
When someone created a new doc, I'd like to be able to set default settings in the admin that they can't change. For example..

I set it globally as : 
This Doc can be read by: Anyone
This Doc can be edited by: Logged-in Users
Comments are visible to: Anyone
Comments can be posted by: Logged-in Users
History can be viewed by: Anyone

And then when someone creates or edits a doc, they can't change it from that and it's set globally for all new docs created.

**Comment by boonebgorges** [comment]
It's unlikely that we'll introduce a new admin-level UI for this, but it can be done with a small plugin. First, to disable the "access" box when editing a Doc:

```php
add_filter( 'bp_docs_allow_access_settings', '__return_false' ); // Or you can provide a custom callback with some more involved logic.
```

To force access settings:

```php
add_filter(
  'bp_docs_get_doc_settings',
  function( $settings, $doc_id ) {
    // You can use $doc_id to do doc-specific things if you want. Otherwise:
    return array(
        'read' => 'anyone',
        'edit' => 'loggedin',
        'read_comments' => 'anyone',
        'post_comments' => 'loggedin',
        'view_history' => 'anyone',
    );
  },
  10,
  2
);
```

**Comment by alieneila** [comment]
Perfect, thank you =)
