### ISSUE TITLE
beaverBuilder and TinyMCE buttons

### ISSUE THREAD

**Issue by Rahe** [boonebgorges/buddypress-docs#677]
Hello,

I have this error with beaver builder :

> ErrorException
> Notice: Undefined offset: 10
> buddypress-docs/includes/templatetags-edit.php in bp_docs_add_external_tinymce_buttons_row1  at line 239
> 

Reference : https://github.com/boonebgorges/buddypress-docs/blob/master/includes/templatetags-edit.php#L239

There is a foreach on the buttons assuming that the keys are numerical and sequential, but into the $buttons variable I have :
{
0: formatselect, 
1: bold, 
2: italic, 
3: bullist, 
4: numlist, 
5: blockquote, 
6: alignleft, 
7: aligncenter, 
8: alignright, 
11: spellchecker, 
12: fullscreen, 
13: wp_adv
}

the index 10 doesn't exists.

**Comment by boonebgorges** [comment]
Thank you for reporting this! The change in 26a2958 should fix the problem.

**Comment by Rahe** [comment]
Nice, thank you :)
