### ISSUE TITLE
404 "Oops! That page can't be found" for /index.php/docs/create/

### ISSUE THREAD

**Issue by stimpy77** [boonebgorges/buddypress-docs#680]
I'm running WP locally on Windows 10 with Apache server (via XAMPP) and WP and BuddyPress are all working normally. The "Create New Doc" button for BP Docs is not working. It's getting an "Oops! That page can’t be found" error. I am able to create a doc item from WP-Admin, but not from the Docs page. (/index.php/docs/)

I'm sure it's a config issue that the installer and/or install instructions might've missed, any idea what needs doing?

**Comment by stimpy77** [comment]
I noticed the same happens with /index.php/docs/doc1/edit/

**Comment by dcavins** [comment]
Try setting your permalinks to a buddypress-friendly setting.

**Comment by stimpy77** [comment]
Thanks.

**Comment by dcavins** [comment]
I'm glad that the simple answer worked! :)
