### ISSUE TITLE
Separate Comments Field 

### ISSUE THREAD

**Issue by paulw32** [boonebgorges/buddypress-docs#683]
Be good to have a separate comments field so that users don't have to edit the doc. Be good if the creator of the document had the ability to prevent edits and only allow people to comment and offer feedback rather than make edits themselves.
Possibly even a star rating system?
I'd actually pay for that.

**Comment by dcavins** [comment]
Comments are generally available for docs (from the doc's read screen) if comments are enabled on your WordPress installation. Give it a try. Comments also have their own level of access--check the access controls for a doc and you'll see controls for 'read', 'edit', 'read_comments', 'post_comments', 'view_history', and 'manage' capabilities.

**Comment by paulw32** [comment]
> Comments are generally available for docs (from the doc's read screen) if comments are enabled on your WordPress installation. Give it a try. Comments also have their own level of access--check the access controls for a doc and you'll see controls for 'read', 'edit', 'read_comments', 'post_comments', 'view_history', and 'manage' capabilities.

Thanks dcavins, there must be something wrong with my wp install. I'll run some updates and see if that fixes it.
