### ISSUE TITLE
Warning buddypress-docs/lib/nuvola

### ISSUE THREAD

**Issue by lindabenefield** [boonebgorges/buddypress-docs#693]
I am getting the following error: 
Warning:  opendir(/home4/brownmaster/developernerds.com/wp-content/plugins/buddypress-docs/lib/nuvola): failed to open dir: No such file or directory in /home4/brownmaster/developernerds.com/wp-includes/post.php on line 6606

I went into the plugin files to the lib folder and created a folder called nuvola and the warning went away. So, why is that there anyways? I know the folder will get erased every time i update the plugin, so I would like a real fix for this. Thanks!

**Comment by boonebgorges** [comment]
Thanks for bringing this to my attention. The Nuvola icons were removed back in 89177b55c4779a2276bc4e7622eb90e921aa6b6d but some of the filters were incorrectly left in place. This will be fixed as part of the next release.
