### ISSUE TITLE
[Question] Integration with BuddyBoss?

### ISSUE THREAD

**Issue by wholebiz** [boonebgorges/buddypress-docs#702]
Hi,

I use the BuddyBoss plugin and theme. They recently added a file system, but it only allows for uploading, not collaborative work like this plugin.  Their file system allows embeds in messages and other places.

Our community would benefit greatly from a collaborative feature as you're providing in this plugin. However, BuddyBoss's media "component" handles a wide range of services. I can't really disable it, but if I attempt to enable their module and your plugin, our website locks up.

Do you see any path forward for us to have your document collaboration feature inside of BuddyBoss?

Thanks!

**Comment by boonebgorges** [comment]
Hi @wholebiz - BuddyBoss is a commercial fork of the open-source BuddyPress. I believe that the BuddyBoss team suggests compatibility between their platform and freely-available tools built for BP, but based on reports I've had here and elsewhere, the compatibility is not always 100%. In any case, the goal of the BuddyPress Docs project is to maintain compatibility with BuddyPress. We haven't got the resources or the inclination to do additional work to test alongside the BuddyBoss platform. That kind of compatibility work is the onus of the BuddyBoss team. I encourage you to reach out to them; as a paying customer, you might have some leverage to have their team take a look at the underlying cause of the incompatibility.

All this being said, if you or the BuddyBoss team is able to point to relatively straightforward changes in BuddyPress Docs that would help with compatibility - such as the addition of certain filters, or whatever - I'd be glad to have a look at the suggestions.

**Comment by wholebiz** [comment]
Thank you. I will do that.
