### ISSUE TITLE
Cannot add files

### ISSUE THREAD

**Issue by theotaurus** [boonebgorges/buddypress-docs#705]
Clicking the 'add file' button results in a 'refresh-look-alike' cycle, ending on the same spot.
Note: in the settings is adding attachments enabled.

**Comment by boonebgorges** [comment]
Are you able to provide a screencast of this behavior?

Also, please open your JavaScript console to see if there are any errors that might point to a problem.

**Comment by dcavins** [comment]
What are the chances that the host has disabled `heartbeat.js`? :)

**Comment by theotaurus** [comment]
dcavins was right. It was the heartbeat. SiteGround Optimizer corrected and then it was fixed. Great because I love this docs-app.

Thx guys :-)

**Comment by dcavins** [comment]
Thanks for the update. Boone has removed the `hearbeat.js` dependency that has caused a fair amount of heartache, and that change is coming in a future update.

**Comment by boonebgorges** [comment]
Excellent! The next version of buddypress-docs will have this fix built in. See #704.
