### ISSUE TITLE
Document page don't take in account the "fullpage" directive 

### ISSUE THREAD

**Issue by Djimi41** [boonebgorges/buddypress-docs#716]
Despite a "document" page is refered in the menu to display the "document" topic, the full page directive of the "portfoliopress" theme is not interpreted to display the page **without** the rigth colomn  (default) . see : [(https://www.artistesduloiretcher.fr/docs/)]
For wordpress, the document content is not considered as a "wordpress page"
The same issue is to display directly  a  "document" taking account of the "fullpage" directive
Could you help to solve this issue (?)  ?

**Comment by dcavins** [comment]
Hello, BP Docs is using what WordPress calls an "archive page" for its display. It will be displayed however your theme chooses to show archives. You can override the template in your theme by adding a more specific file for just the `bp_docs` post type. Basically, create a copy of your theme's `archive.php` (name the copy `archive-bp_doc.php` so that it applies to only this post type) and change the code to suit.

**Comment by Djimi41** [comment]
don't run with archive-bp-doc.php ... i have supposed that code changes are for archive-bp-doc.php file **only**. Is it necessary to modify other files ?

**Comment by dcavins** [comment]
The name of the file you add to your theme must be exactly: `archive-bp_doc.php` (note the underscore).

**Comment by Djimi41** [comment]
the name of the file is correct, i mean with an underscore, the fault i've made is only in my message, sorry. I have this 2 files archive.php and archive-bp_doc.php in the same porfolio-press themes' directory

**Comment by dcavins** [comment]
Hmm. I'd install Query Monitor to see what template your theme is supplying. https://wordpress.org/plugins/query-monitor/ Load the Docs library, then click the Query Monitor button in the toolbar and look for the "Template" entry.

**Comment by Djimi41** [comment]
So it is not the archive.php  which is used  but page.php
and for the fullwidth pages , the model should be   : templates/full-width-page.php
how to activate archive.php or archive-bp_doc.php first  please ?
