### ISSUE TITLE
Add license meta information

### ISSUE THREAD

**Issue by BradleyScrim** [boonebgorges/buddypress-docs#718]
Hi,

we'd like to use your plugin in our project, but there is no license stated in your [readme](https://github.com/boonebgorges/buddypress-docs/blob/master/readme.txt), also there is no license-file.
This is a standard feature in all other WordPress-Plugins we're using. [Example for BuddyPress](https://plugins.svn.wordpress.org/buddypress/trunk/).

Thanks!

**Comment by boonebgorges** [comment]
Thanks for pointing out this omission.

The plugin's license is GPL v3.0. I've updated the readme.txt header in the 2.1.x branch and it will be part of the next release. https://github.com/boonebgorges/buddypress-docs/tree/2.1.x#readme
