### ISSUE TITLE
Purpose of 'item' tag archive pages?

### ISSUE THREAD

**Issue by gyrus** [boonebgorges/buddypress-docs#722]
Hi, I've just discovered a large number of pages on a client site which appear to be 'archives' for the `bp_docs_tag` taxonomy, with a link structure: `/item/[tag_slug]/`.

I'm trying to work out what their purpose is, what template they're using, etc. It looks like they're defaulting to my custom theme's `index.php` and just outputting the content from the first item related to the tag.

I can't find any real documentation on this aspect of the plugin. There seems to be a series of templates in the plugin but I don't think they're being used - at least, there doesn't seem to be one for this tags archive. Should there be a template that simply outputs a list of docs related to the tag?

**Comment by gyrus** [comment]
As far as I can tell, on our site in most places where you can view docs, they're associated with groups. And clicking on a doc tag takes you to a (functioning) list of docs in that group with that tag. I assume `/item/` is supposed to list docs related to the tag across all groups?

**Comment by boonebgorges** [comment]
It wasn't really built for any purpose. It's just an artifact of `public=true` when registering the post type. 

> As far as I can tell, on our site in most places where you can view docs, they're associated with groups. And clicking on a doc tag takes you to a (functioning) list of docs in that group with that tag. I assume /item/ is supposed to list docs related to the tag across all groups?

The plugin supports the use of docs outside of groups, but whether that's useful or used on your site depends on your purposes.

If you don't want this, you can disable by filtering 'bp_docs_post_type_args' and setting `'has_archive'` to `false`.

**Comment by gyrus** [comment]
Thanks, I'll probably just deactivate these then. However, I'm not sure the `bp_docs_post_type_args` filter is right. This is the post type args for the `bp_doc` post type, and here I'm looking at the `bp_docs_tag` taxonomy.

I can see the taxonomy being registered in `/includes/addon-taxonomy.php` but the args don't seem to be filtered. I don't think the core `register_taxonomy()` has an internal filter for the args either. Any ideas?

**Comment by boonebgorges** [comment]
Oh right, good call. Looking at this further, I think there's no need to have `/blog/item`, because the content of a tag is meant to be viewed at /docs/`. I've removed it in 0ad2a19

**Comment by gyrus** [comment]
Excellent, many thanks!

**Comment by gyrus** [comment]
Says here 'added this to the 2.1.7 milestone' - but the current version of the plugin is 2.1.8? I'm patching this on our site anyway, I assumed it'll be in the next release.

**Comment by boonebgorges** [comment]
Thanks for the heads up about the milestone.
