### ISSUE TITLE
attachments are not opened but downloaded

### ISSUE THREAD

**Issue by MarAmsterdam** [boonebgorges/buddypress-docs#723]
Buddy Docs: attachments are not opened but downloaded to device. I want attachments to be opened on screen. How to solve this?

**Comment by boonebgorges** [comment]
Hello and thanks for the ticket. See https://github.com/boonebgorges/buddypress-docs/issues/659#issuecomment-521731262 for a solution.

**Comment by MarAmsterdam** [comment]
That #659 works fine, thanks!  One more question: Is it possible to assign categories to BP Docs? I wish users could place a document directly in a specific category. 
Like blogs, can be placed in a specific category. A document only in specific groups.
