### ISSUE TITLE
Improved content width for CPT pages in certain themes

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#731]
BP pages use the full width styles on certain WP themes. For example, a group page running twentytwentyone:

![Screenshot_2023-10-26_20-50-50](https://github.com/boonebgorges/buddypress-docs/assets/246627/1a3fbf26-9b04-4231-bf6b-fcb81922987f)

In contrast, Docs CPT pages have a very limited width:

![Screenshot_2023-10-26_20-51-27](https://github.com/boonebgorges/buddypress-docs/assets/246627/af9cbcf8-4d28-4422-a377-aeeae87de8a8)

Is there some change we can make to the markup of our CPT pages, perhaps a certain wrapper class or something, that will cause them to use the same width declarations as BP pages? Or perhaps we need to have our own theme-specific fixes like BP does? Possibly related: #730 

@dcavins Maybe you could  take a moment thinking about this?

**Comment by dcavins** [comment]
Hi Boone, I'd be happy to look at this. Should PRs be made against the 2.2 branch?

**Comment by boonebgorges** [comment]
Thanks, David! Yes, the 2.2 branch should be fine. I'm working on a special BP 12 compatibility branch, but I can't imagine it'll conflict much with theme-related changes.

**Comment by dcavins** [comment]
With the update, in Twentytwenty (similar in '19, '20 and '21):
![wide-docs-directory](https://github.com/boonebgorges/buddypress-docs/assets/1391994/f26676a9-462d-4ad0-9ee5-648f78219ccd)

**Comment by boonebgorges** [comment]
Moving to the 2.2.1 milestone as work is happening in the #738 branch that affects this.

**Comment by boonebgorges** [comment]
There's more work to be done here with specific themes. See https://github.com/boonebgorges/buddypress-docs/issues/728#issuecomment-1863753818. But let's go with what we've got for 2.2.1.
