### ISSUE TITLE
upload issue - new fan

### ISSUE THREAD

**Issue by Ifassaha** [boonebgorges/buddypress-docs#732]
Hi, maybe it is not the good place to post this (?) / sorry if it isnt
this tool would be EXACTLY what I need with some enhancements : 
First, I meet some issues on uploading attachment files. And after, allow and ease sending from a mobile would be fantastic ! 
I am not a dev, but I would be happy to contribute. How can I help?

**Comment by boonebgorges** [comment]
Can you say more about your problems with uploading attachment files?
