### ISSUE TITLE
Add media button on front end

### ISSUE THREAD

**Issue by chrisjoshuamartin** [boonebgorges/buddypress-docs#758]
Possibiliy of having the add media button on the front end view similar to the backend would be nice.

<img width="703" alt="Screenshot 2024-10-17 at 10 21 18 AM" src="https://github.com/user-attachments/assets/1187159f-49a1-4685-9192-385266e099fd">

**Comment by chrisjoshuamartin** [comment]
Also Im guessing there is a good reason its not on the frontend, heh

**Comment by boonebgorges** [comment]
Thanks for the idea. The button was never added there for two reasons. One is that it would require improved processing of content on the front end. For example, if you allow images to be inserted, we have to make sure that the markup is sanitized correctly, that images don't spill out of the container when reading, etc. The other, more important reason is that the media library, as it exists in WP, allows all users to share access to the same set of media items. So if I upload image A, you can see A when you use Add Media to choose an existing file. But Docs can be created within groups and with different privacy settings. So we would want to limit access based on those limitations, a process that is complex and subject to error. That's not to say it couldn't be done, just that it's never been a priority.

See also #699, #659, and especially #569

**Comment by chrisjoshuamartin** [comment]
I appreciate the reply and figured there was a reason. Thanks for the references, I'll give them a review.
