### ISSUE TITLE
Auto linking to existing doc titles

### ISSUE THREAD

**Issue by skippybosco** [boonebgorges/buddypress-docs#79]
The ability to auto-link text that exact matches an existing Buddypress Doc titles to the corresponding doc. 

A couple of considerations that come to mind: 

1) Not sure if this is better served as an additional Wordpress / Buddypress plugin, or to be built within the core of the buddypress docs plugin?

2) Should the linking to docs only happen from within other documents or should this functionality be extended throughout Buddypress?

**Comment by boonebgorges** [comment]
Great idea, but I haven't got the time to implement. If anyone would like to have a shot at it, please feel free to send a PR - keep in mind that contextual links should be sensitive to doc privacy settings.
