### ISSUE TITLE
Doc count in tab

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/buddypress-docs#81]
See http://buddypress.org/community/groups/buddypress-docs/forum/topic/can-we-have-docs-count-in-docs-tab/

**Comment by mecanographik** [comment]
Hi Boone, could you tell me when the "group doc tab count" feature will be available, on the next stable release? 
Regards,

**Comment by boonebgorges** [comment]
Hi Pierre,

No guarantees. As I recall, there are complications that make it 
difficult to do. That's why the previous implementation was removed. 
I'll update this ticket if it's added again.
