### ISSUE TITLE
dtree implementation + toggle doc descriptions in view docs

### ISSUE THREAD

**Issue by danfolt** [boonebgorges/buddypress-docs#84]
Hello I have some suggestions :
Can you make some hierarchy for parent docs – viewable in view docs ?
I think It is not enough to see the link only on the bottom of the doc , nobody notices that ,
like here:
http://www.4ella.com/groups/dancersrecruit-com/docs/plat-tanecnice
better to have it sorted in VIEW DOCS (the best would be dtree folders- I know Boone that you don’t like them -:)
2. I see that author of this plugin loves using toggle buttons , why don’t you add toggle (+) to view docs excerps descriptions , the view docs page will look smaller and better understandable when there will be only the titels .

Thanks for this plugin !

**Comment by boonebgorges** [comment]
This is a great idea but I'm afraid it won't happen without outside help.
