### ISSUE TITLE
Docs icons in the first column of view Docs

### ISSUE THREAD

**Issue by danfolt** [boonebgorges/buddypress-docs#89]
Hello Boone , whats the purpose of the  first empty column in View Docs ? , I have added doc icon and it looks nice and also more descriptive  , but I think that much more better it would look with possibility to add any predefined icon as : warning icon , document icon , info icon , help icon , sticky icon , possibilities are endless etc . View Docs should be more descriptive , I wouldn't add image upload to that column but I would add below images folder - icon folder,  where plugin author  or admins should insert set of icons and I would ask (with dropdown menu ?)  to docs creators - members / admins which icon should represent their single document .

**Comment by boonebgorges** [comment]
A few versions ago, we introduced some basic icons for some kinds of attachments.
